// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const featureStats = `-- name: FeatureStats :one
SELECT count(*) FILTER (WHERE f.error = '' AND f.version = $1::int)::bigint AS analyzed,
       count(*) FILTER (WHERE f.error <> '')::bigint AS failed,
       (SELECT count(*) FROM reco.tracks WHERE deleted_at IS NULL)::bigint AS tracks
FROM reco.track_features f JOIN reco.tracks t ON t.id = f.track_id AND t.deleted_at IS NULL
`

type FeatureStatsRow struct {
	Analyzed int64
	Failed   int64
	Tracks   int64
}

func (q *Queries) FeatureStats(ctx context.Context, version int32) (FeatureStatsRow, error) {
	row := q.db.QueryRow(ctx, featureStats, version)
	var i FeatureStatsRow
	err := row.Scan(&i.Analyzed, &i.Failed, &i.Tracks)
	return i, err
}

const listActiveTracks = `-- name: ListActiveTracks :many
SELECT t.id, t.title, t.artist_id, t.artist, t.album_id, t.album, t.genre, t.year, t.duration_sec, t.popularity, t.created_at,
       COALESCE(f.raw, '{}'::real[])::real[] AS raw, COALESCE(f.version, 0)::int AS feature_version
FROM reco.tracks t
LEFT JOIN reco.track_features f ON f.track_id = t.id AND f.error = ''
WHERE t.deleted_at IS NULL
ORDER BY t.id
`

type ListActiveTracksRow struct {
	ID             uuid.UUID
	Title          string
	ArtistID       uuid.UUID
	Artist         string
	AlbumID        *uuid.UUID
	Album          string
	Genre          string
	Year           *int32
	DurationSec    int32
	Popularity     float32
	CreatedAt      time.Time
	Raw            []float32
	FeatureVersion int32
}

func (q *Queries) ListActiveTracks(ctx context.Context) ([]ListActiveTracksRow, error) {
	rows, err := q.db.Query(ctx, listActiveTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTracksRow
	for rows.Next() {
		var i ListActiveTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.Artist,
			&i.AlbumID,
			&i.Album,
			&i.Genre,
			&i.Year,
			&i.DurationSec,
			&i.Popularity,
			&i.CreatedAt,
			&i.Raw,
			&i.FeatureVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTracksDeleted = `-- name: MarkTracksDeleted :execrows
UPDATE reco.tracks SET deleted_at = now() WHERE deleted_at IS NULL AND synced_at < $1
`

func (q *Queries) MarkTracksDeleted(ctx context.Context, syncedBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, markTracksDeleted, syncedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAnalysisError = `-- name: RecordAnalysisError :exec
INSERT INTO reco.track_features (track_id, version, error, attempts, analyzed_at)
VALUES ($1, $2, $3, 1, now())
ON CONFLICT (track_id) DO UPDATE SET error = EXCLUDED.error, attempts = reco.track_features.attempts + 1, analyzed_at = now()
`

type RecordAnalysisErrorParams struct {
	TrackID uuid.UUID
	Version int32
	Error   string
}

func (q *Queries) RecordAnalysisError(ctx context.Context, arg RecordAnalysisErrorParams) error {
	_, err := q.db.Exec(ctx, recordAnalysisError, arg.TrackID, arg.Version, arg.Error)
	return err
}

const trackKeys = `-- name: TrackKeys :one
SELECT artist_id, album_id, genre FROM reco.tracks WHERE id = $1
`

type TrackKeysRow struct {
	ArtistID uuid.UUID
	AlbumID  *uuid.UUID
	Genre    string
}

func (q *Queries) TrackKeys(ctx context.Context, id uuid.UUID) (TrackKeysRow, error) {
	row := q.db.QueryRow(ctx, trackKeys, id)
	var i TrackKeysRow
	err := row.Scan(&i.ArtistID, &i.AlbumID, &i.Genre)
	return i, err
}

const tracksNeedingAnalysis = `-- name: TracksNeedingAnalysis :many
SELECT t.id FROM reco.tracks t
LEFT JOIN reco.track_features f ON f.track_id = t.id
WHERE t.deleted_at IS NULL
  AND (f.track_id IS NULL
       OR f.version < $1::int
       OR (f.error <> '' AND f.attempts < $2::int AND f.analyzed_at < now() - interval '30 minutes'))
ORDER BY t.created_at DESC, t.id
LIMIT $3
`

type TracksNeedingAnalysisParams struct {
	Version     int32
	MaxAttempts int32
	Lim         int32
}

func (q *Queries) TracksNeedingAnalysis(ctx context.Context, arg TracksNeedingAnalysisParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, tracksNeedingAnalysis, arg.Version, arg.MaxAttempts, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatures = `-- name: UpsertFeatures :exec
INSERT INTO reco.track_features (track_id, version, tempo, energy, loudness_db, centroid, flatness, valence, raw, error, attempts, analyzed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::real[], '', 0, now())
ON CONFLICT (track_id) DO UPDATE SET
    version = EXCLUDED.version, tempo = EXCLUDED.tempo, energy = EXCLUDED.energy, loudness_db = EXCLUDED.loudness_db,
    centroid = EXCLUDED.centroid, flatness = EXCLUDED.flatness, valence = EXCLUDED.valence, raw = EXCLUDED.raw,
    error = '', attempts = 0, analyzed_at = now()
`

type UpsertFeaturesParams struct {
	TrackID    uuid.UUID
	Version    int32
	Tempo      float32
	Energy     float32
	LoudnessDb float32
	Centroid   float32
	Flatness   float32
	Valence    float32
	Raw        []float32
}

func (q *Queries) UpsertFeatures(ctx context.Context, arg UpsertFeaturesParams) error {
	_, err := q.db.Exec(ctx, upsertFeatures,
		arg.TrackID,
		arg.Version,
		arg.Tempo,
		arg.Energy,
		arg.LoudnessDb,
		arg.Centroid,
		arg.Flatness,
		arg.Valence,
		arg.Raw,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO reco.tracks (id, title, artist_id, artist, album_id, album, genre, year, duration_sec, popularity, created_at, synced_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NULL)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title, artist_id = EXCLUDED.artist_id, artist = EXCLUDED.artist, album_id = EXCLUDED.album_id,
    album = EXCLUDED.album, genre = EXCLUDED.genre, year = EXCLUDED.year, duration_sec = EXCLUDED.duration_sec,
    popularity = EXCLUDED.popularity, synced_at = EXCLUDED.synced_at, deleted_at = NULL
`

type UpsertTrackParams struct {
	ID          uuid.UUID
	Title       string
	ArtistID    uuid.UUID
	Artist      string
	AlbumID     *uuid.UUID
	Album       string
	Genre       string
	Year        *int32
	DurationSec int32
	Popularity  float32
	CreatedAt   time.Time
	SyncedAt    time.Time
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.Exec(ctx, upsertTrack,
		arg.ID,
		arg.Title,
		arg.ArtistID,
		arg.Artist,
		arg.AlbumID,
		arg.Album,
		arg.Genre,
		arg.Year,
		arg.DurationSec,
		arg.Popularity,
		arg.CreatedAt,
		arg.SyncedAt,
	)
	return err
}
