// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertItemFactors implements pgx.CopyFromSource.
type iteratorForInsertItemFactors struct {
	rows                 []InsertItemFactorsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertItemFactors) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertItemFactors) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TrackID,
		r.rows[0].Factors,
	}, nil
}

func (r iteratorForInsertItemFactors) Err() error {
	return nil
}

func (q *Queries) InsertItemFactors(ctx context.Context, arg []InsertItemFactorsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"reco", "item_factors"}, []string{"track_id", "factors"}, &iteratorForInsertItemFactors{rows: arg})
}

// iteratorForInsertNeighbors implements pgx.CopyFromSource.
type iteratorForInsertNeighbors struct {
	rows                 []InsertNeighborsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertNeighbors) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertNeighbors) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TrackID,
		r.rows[0].Source,
		r.rows[0].NeighborID,
		r.rows[0].Sim,
	}, nil
}

func (r iteratorForInsertNeighbors) Err() error {
	return nil
}

func (q *Queries) InsertNeighbors(ctx context.Context, arg []InsertNeighborsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"reco", "item_neighbors"}, []string{"track_id", "source", "neighbor_id", "sim"}, &iteratorForInsertNeighbors{rows: arg})
}

// iteratorForInsertUserFactors implements pgx.CopyFromSource.
type iteratorForInsertUserFactors struct {
	rows                 []InsertUserFactorsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertUserFactors) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertUserFactors) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Factors,
	}, nil
}

func (r iteratorForInsertUserFactors) Err() error {
	return nil
}

func (q *Queries) InsertUserFactors(ctx context.Context, arg []InsertUserFactorsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"reco", "user_factors"}, []string{"user_id", "factors"}, &iteratorForInsertUserFactors{rows: arg})
}
