// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteItemFactors = `-- name: DeleteItemFactors :exec
DELETE FROM reco.item_factors
`

func (q *Queries) DeleteItemFactors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteItemFactors)
	return err
}

const deleteNeighbors = `-- name: DeleteNeighbors :exec
DELETE FROM reco.item_neighbors WHERE source = $1
`

func (q *Queries) DeleteNeighbors(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, deleteNeighbors, source)
	return err
}

const deleteUserFactors = `-- name: DeleteUserFactors :exec
DELETE FROM reco.user_factors
`

func (q *Queries) DeleteUserFactors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUserFactors)
	return err
}

const getState = `-- name: GetState :one
SELECT value FROM reco.state WHERE key = $1
`

func (q *Queries) GetState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserFactors = `-- name: GetUserFactors :one
SELECT factors FROM reco.user_factors WHERE user_id = $1
`

func (q *Queries) GetUserFactors(ctx context.Context, userID uuid.UUID) ([]float32, error) {
	row := q.db.QueryRow(ctx, getUserFactors, userID)
	var factors []float32
	err := row.Scan(&factors)
	return factors, err
}

type InsertItemFactorsParams struct {
	TrackID uuid.UUID
	Factors []float32
}

type InsertNeighborsParams struct {
	TrackID    uuid.UUID
	Source     string
	NeighborID uuid.UUID
	Sim        float32
}

type InsertUserFactorsParams struct {
	UserID  uuid.UUID
	Factors []float32
}

const listItemFactors = `-- name: ListItemFactors :many
SELECT track_id, factors FROM reco.item_factors
`

func (q *Queries) ListItemFactors(ctx context.Context) ([]RecoItemFactor, error) {
	rows, err := q.db.Query(ctx, listItemFactors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoItemFactor
	for rows.Next() {
		var i RecoItemFactor
		if err := rows.Scan(&i.TrackID, &i.Factors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNeighbors = `-- name: ListNeighbors :many
SELECT track_id, source, neighbor_id, sim FROM reco.item_neighbors
`

func (q *Queries) ListNeighbors(ctx context.Context) ([]RecoItemNeighbor, error) {
	rows, err := q.db.Query(ctx, listNeighbors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoItemNeighbor
	for rows.Next() {
		var i RecoItemNeighbor
		if err := rows.Scan(
			&i.TrackID,
			&i.Source,
			&i.NeighborID,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setState = `-- name: SetState :exec
INSERT INTO reco.state (key, value, updated_at) VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type SetStateParams struct {
	Key   string
	Value string
}

func (q *Queries) SetState(ctx context.Context, arg SetStateParams) error {
	_, err := q.db.Exec(ctx, setState, arg.Key, arg.Value)
	return err
}
