// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type RecoIngested struct {
	Key string
	At  time.Time
}

type RecoItemFactor struct {
	TrackID uuid.UUID
	Factors []float32
}

type RecoItemNeighbor struct {
	TrackID    uuid.UUID
	Source     string
	NeighborID uuid.UUID
	Sim        float32
}

type RecoSourceStat struct {
	UserID uuid.UUID
	Source string
	Alpha  float64
	Beta   float64
}

type RecoState struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type RecoTrack struct {
	ID          uuid.UUID
	Title       string
	ArtistID    uuid.UUID
	Artist      string
	AlbumID     *uuid.UUID
	Album       string
	Genre       string
	Year        *int32
	DurationSec int32
	Popularity  float32
	CreatedAt   time.Time
	SyncedAt    time.Time
	DeletedAt   *time.Time
}

type RecoTrackFeature struct {
	TrackID    uuid.UUID
	Version    int32
	Tempo      float32
	Energy     float32
	LoudnessDb float32
	Centroid   float32
	Flatness   float32
	Valence    float32
	Raw        []float32
	Error      string
	Attempts   int32
	AnalyzedAt time.Time
}

type RecoUserFactor struct {
	UserID  uuid.UUID
	Factors []float32
}

type RecoUserTaste struct {
	UserID    uuid.UUID
	Kind      string
	Key       string
	Weight    float64
	UpdatedAt time.Time
}

type RecoUserTrack struct {
	UserID       uuid.UUID
	TrackID      uuid.UUID
	Affinity     float64
	AffinityAt   time.Time
	Plays        int32
	Completes    int32
	EarlySkips   int32
	Skips        int32
	PlaylistAdds int32
	Liked        bool
	LastPlayed   *time.Time
}
