// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSourceStat = `-- name: AddSourceStat :exec
INSERT INTO reco.source_stats (user_id, source, alpha, beta) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, source) DO UPDATE SET alpha = reco.source_stats.alpha + EXCLUDED.alpha, beta = reco.source_stats.beta + EXCLUDED.beta
`

type AddSourceStatParams struct {
	UserID uuid.UUID
	Source string
	Alpha  float64
	Beta   float64
}

func (q *Queries) AddSourceStat(ctx context.Context, arg AddSourceStatParams) error {
	_, err := q.db.Exec(ctx, addSourceStat,
		arg.UserID,
		arg.Source,
		arg.Alpha,
		arg.Beta,
	)
	return err
}

const addTaste = `-- name: AddTaste :exec
INSERT INTO reco.user_taste AS t (user_id, kind, key, weight, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, kind, key) DO UPDATE SET
    weight = CASE WHEN EXCLUDED.updated_at >= t.updated_at
        THEN t.weight * power(0.5, extract(epoch FROM (EXCLUDED.updated_at - t.updated_at))::float8 / $6::float8) + EXCLUDED.weight
        ELSE t.weight + EXCLUDED.weight * power(0.5, extract(epoch FROM (t.updated_at - EXCLUDED.updated_at))::float8 / $6::float8)
    END,
    updated_at = greatest(t.updated_at, EXCLUDED.updated_at)
`

type AddTasteParams struct {
	UserID      uuid.UUID
	Kind        string
	Key         string
	Delta       float64
	EventAt     time.Time
	HalfLifeSec float64
}

// AddTaste mirrors profile.Accumulate: decay the stored weight to the event time
// and add the delta; an older event is decayed to the stored time instead.
func (q *Queries) AddTaste(ctx context.Context, arg AddTasteParams) error {
	_, err := q.db.Exec(ctx, addTaste,
		arg.UserID,
		arg.Kind,
		arg.Key,
		arg.Delta,
		arg.EventAt,
		arg.HalfLifeSec,
	)
	return err
}

const cleanupIngested = `-- name: CleanupIngested :execrows
DELETE FROM reco.ingested WHERE at < $1
`

func (q *Queries) CleanupIngested(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupIngested, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserTrack = `-- name: GetUserTrack :one
SELECT user_id, track_id, affinity, affinity_at, plays, completes, early_skips, skips, playlist_adds, liked, last_played FROM reco.user_tracks WHERE user_id = $1 AND track_id = $2 FOR UPDATE
`

type GetUserTrackParams struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

func (q *Queries) GetUserTrack(ctx context.Context, arg GetUserTrackParams) (RecoUserTrack, error) {
	row := q.db.QueryRow(ctx, getUserTrack, arg.UserID, arg.TrackID)
	var i RecoUserTrack
	err := row.Scan(
		&i.UserID,
		&i.TrackID,
		&i.Affinity,
		&i.AffinityAt,
		&i.Plays,
		&i.Completes,
		&i.EarlySkips,
		&i.Skips,
		&i.PlaylistAdds,
		&i.Liked,
		&i.LastPlayed,
	)
	return i, err
}

const listSourceStats = `-- name: ListSourceStats :many
SELECT source, alpha, beta FROM reco.source_stats WHERE user_id = $1
`

type ListSourceStatsRow struct {
	Source string
	Alpha  float64
	Beta   float64
}

func (q *Queries) ListSourceStats(ctx context.Context, userID uuid.UUID) ([]ListSourceStatsRow, error) {
	rows, err := q.db.Query(ctx, listSourceStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceStatsRow
	for rows.Next() {
		var i ListSourceStatsRow
		if err := rows.Scan(&i.Source, &i.Alpha, &i.Beta); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTaste = `-- name: ListUserTaste :many
SELECT kind, key, weight, updated_at FROM reco.user_taste WHERE user_id = $1
`

type ListUserTasteRow struct {
	Kind      string
	Key       string
	Weight    float64
	UpdatedAt time.Time
}

func (q *Queries) ListUserTaste(ctx context.Context, userID uuid.UUID) ([]ListUserTasteRow, error) {
	rows, err := q.db.Query(ctx, listUserTaste, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTasteRow
	for rows.Next() {
		var i ListUserTasteRow
		if err := rows.Scan(
			&i.Kind,
			&i.Key,
			&i.Weight,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTracks = `-- name: ListUserTracks :many
SELECT user_id, track_id, affinity, affinity_at, plays, completes, early_skips, skips, playlist_adds, liked, last_played FROM reco.user_tracks WHERE user_id = $1
`

func (q *Queries) ListUserTracks(ctx context.Context, userID uuid.UUID) ([]RecoUserTrack, error) {
	rows, err := q.db.Query(ctx, listUserTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoUserTrack
	for rows.Next() {
		var i RecoUserTrack
		if err := rows.Scan(
			&i.UserID,
			&i.TrackID,
			&i.Affinity,
			&i.AffinityAt,
			&i.Plays,
			&i.Completes,
			&i.EarlySkips,
			&i.Skips,
			&i.PlaylistAdds,
			&i.Liked,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIngested = `-- name: MarkIngested :execrows
INSERT INTO reco.ingested (key) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) MarkIngested(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, markIngested, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const positiveAffinities = `-- name: PositiveAffinities :many
SELECT user_id, track_id, affinity, affinity_at FROM reco.user_tracks WHERE affinity > 0
`

type PositiveAffinitiesRow struct {
	UserID     uuid.UUID
	TrackID    uuid.UUID
	Affinity   float64
	AffinityAt time.Time
}

func (q *Queries) PositiveAffinities(ctx context.Context) ([]PositiveAffinitiesRow, error) {
	rows, err := q.db.Query(ctx, positiveAffinities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PositiveAffinitiesRow
	for rows.Next() {
		var i PositiveAffinitiesRow
		if err := rows.Scan(
			&i.UserID,
			&i.TrackID,
			&i.Affinity,
			&i.AffinityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileCounts = `-- name: ProfileCounts :one
SELECT count(*)::bigint AS tracks, COALESCE(sum(plays), 0)::bigint AS plays, count(*) FILTER (WHERE liked)::bigint AS likes,
       COALESCE(sum(early_skips), 0)::bigint AS early_skips
FROM reco.user_tracks WHERE user_id = $1
`

type ProfileCountsRow struct {
	Tracks     int64
	Plays      int64
	Likes      int64
	EarlySkips int64
}

func (q *Queries) ProfileCounts(ctx context.Context, userID uuid.UUID) (ProfileCountsRow, error) {
	row := q.db.QueryRow(ctx, profileCounts, userID)
	var i ProfileCountsRow
	err := row.Scan(
		&i.Tracks,
		&i.Plays,
		&i.Likes,
		&i.EarlySkips,
	)
	return i, err
}

const upsertUserTrack = `-- name: UpsertUserTrack :exec
INSERT INTO reco.user_tracks (user_id, track_id, affinity, affinity_at, plays, completes, early_skips, skips, playlist_adds, liked, last_played)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id, track_id) DO UPDATE SET
    affinity = EXCLUDED.affinity, affinity_at = EXCLUDED.affinity_at, plays = EXCLUDED.plays, completes = EXCLUDED.completes,
    early_skips = EXCLUDED.early_skips, skips = EXCLUDED.skips, playlist_adds = EXCLUDED.playlist_adds,
    liked = EXCLUDED.liked, last_played = EXCLUDED.last_played
`

type UpsertUserTrackParams struct {
	UserID       uuid.UUID
	TrackID      uuid.UUID
	Affinity     float64
	AffinityAt   time.Time
	Plays        int32
	Completes    int32
	EarlySkips   int32
	Skips        int32
	PlaylistAdds int32
	Liked        bool
	LastPlayed   *time.Time
}

func (q *Queries) UpsertUserTrack(ctx context.Context, arg UpsertUserTrackParams) error {
	_, err := q.db.Exec(ctx, upsertUserTrack,
		arg.UserID,
		arg.TrackID,
		arg.Affinity,
		arg.AffinityAt,
		arg.Plays,
		arg.Completes,
		arg.EarlySkips,
		arg.Skips,
		arg.PlaylistAdds,
		arg.Liked,
		arg.LastPlayed,
	)
	return err
}
