// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type AcquisitionEvent struct {
	ID        int64
	RequestID uuid.UUID
	At        time.Time
	Kind      string
	UserID    *uuid.UUID
	Detail    []byte
}

type AcquisitionRequest struct {
	ID               uuid.UUID
	ReleaseGroupMbid uuid.UUID
	ReleaseMbid      *uuid.UUID
	ArtistMbid       *uuid.UUID
	ArtistName       string
	AlbumTitle       string
	Year             int32
	State            string
	Priority         int32
	ErrorCode        string
	TorrentHash      string
	ReleaseTitle     string
	Indexer          string
	Quality          string
	FileExt          string
	SizeBytes        int64
	Seeders          int32
	Progress         float32
	LidarrAlbumID    *int32
	ImportMode       string
	Attempts         int32
	RequestedBy      uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	StartedAt        *time.Time
	LastProgressAt   *time.Time
	CompletedAt      *time.Time
}

type AcquisitionRequestTrack struct {
	RequestID     uuid.UUID
	RecordingMbid uuid.UUID
	Disc          int32
	Position      int32
	Title         string
	LengthMs      int32
	FileIndex     *int32
	FileName      string
	FileSize      int64
	LibraryPath   string
	WantedAt      *time.Time
}

type AcquisitionRequestUser struct {
	RequestID uuid.UUID
	UserID    uuid.UUID
	Reason    string
	CreatedAt time.Time
}
