// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRequestUser = `-- name: AddRequestUser :execrows
INSERT INTO acquisition.request_users (request_id, user_id, reason) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddRequestUserParams struct {
	RequestID uuid.UUID
	UserID    uuid.UUID
	Reason    string
}

func (q *Queries) AddRequestUser(ctx context.Context, arg AddRequestUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, addRequestUser, arg.RequestID, arg.UserID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpPriority = `-- name: BumpPriority :exec
UPDATE acquisition.requests SET priority = GREATEST(priority, $1), updated_at = now() WHERE id = $2
`

type BumpPriorityParams struct {
	Priority int32
	ID       uuid.UUID
}

func (q *Queries) BumpPriority(ctx context.Context, arg BumpPriorityParams) error {
	_, err := q.db.Exec(ctx, bumpPriority, arg.Priority, arg.ID)
	return err
}

const claimQueued = `-- name: ClaimQueued :many
UPDATE acquisition.requests SET state = 'searching', started_at = now(), updated_at = now()
WHERE id IN (
    SELECT id FROM acquisition.requests WHERE state = 'queued'
    ORDER BY priority DESC, created_at LIMIT $1 FOR UPDATE SKIP LOCKED
)
RETURNING id, release_group_mbid, release_mbid, artist_mbid, artist_name, album_title, year, state, priority, error_code, torrent_hash, release_title, indexer, quality, file_ext, size_bytes, seeders, progress, lidarr_album_id, import_mode, attempts, requested_by, created_at, updated_at, started_at, last_progress_at, completed_at
`

// Moves up to @lim queued requests to "searching" (highest priority first).
func (q *Queries) ClaimQueued(ctx context.Context, lim int32) ([]AcquisitionRequest, error) {
	rows, err := q.db.Query(ctx, claimQueued, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquisitionRequest
	for rows.Next() {
		var i AcquisitionRequest
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseGroupMbid,
			&i.ReleaseMbid,
			&i.ArtistMbid,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.Year,
			&i.State,
			&i.Priority,
			&i.ErrorCode,
			&i.TorrentHash,
			&i.ReleaseTitle,
			&i.Indexer,
			&i.Quality,
			&i.FileExt,
			&i.SizeBytes,
			&i.Seeders,
			&i.Progress,
			&i.LidarrAlbumID,
			&i.ImportMode,
			&i.Attempts,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.LastProgressAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActive = `-- name: CountActive :one
SELECT count(*) FROM acquisition.requests WHERE state IN ('searching', 'downloading', 'importing')
`

func (q *Queries) CountActive(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countByState = `-- name: CountByState :many
SELECT state, count(*)::bigint AS n FROM acquisition.requests GROUP BY state
`

type CountByStateRow struct {
	State string
	N     int64
}

func (q *Queries) CountByState(ctx context.Context) ([]CountByStateRow, error) {
	rows, err := q.db.Query(ctx, countByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountByStateRow
	for rows.Next() {
		var i CountByStateRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUserActive = `-- name: CountUserActive :one
SELECT count(*) FROM acquisition.requests
WHERE requested_by = $1 AND state IN ('queued', 'searching', 'downloading', 'importing')
`

func (q *Queries) CountUserActive(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActive, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserRequestsSince = `-- name: CountUserRequestsSince :one
SELECT count(*) FROM acquisition.requests WHERE requested_by = $1 AND created_at > $2
`

type CountUserRequestsSinceParams struct {
	UserID uuid.UUID
	Since  time.Time
}

func (q *Queries) CountUserRequestsSince(ctx context.Context, arg CountUserRequestsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRequestsSince, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO acquisition.events (request_id, kind, user_id, detail) VALUES ($1, $2, $3, $4)
`

type InsertEventParams struct {
	RequestID uuid.UUID
	Kind      string
	UserID    *uuid.UUID
	Detail    []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.RequestID,
		arg.Kind,
		arg.UserID,
		arg.Detail,
	)
	return err
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO acquisition.requests (id, release_group_mbid, release_mbid, artist_mbid, artist_name, album_title, year, priority, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertRequestParams struct {
	ID               uuid.UUID
	ReleaseGroupMbid uuid.UUID
	ReleaseMbid      *uuid.UUID
	ArtistMbid       *uuid.UUID
	ArtistName       string
	AlbumTitle       string
	Year             int32
	Priority         int32
	RequestedBy      uuid.UUID
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.Exec(ctx, insertRequest,
		arg.ID,
		arg.ReleaseGroupMbid,
		arg.ReleaseMbid,
		arg.ArtistMbid,
		arg.ArtistName,
		arg.AlbumTitle,
		arg.Year,
		arg.Priority,
		arg.RequestedBy,
	)
	return err
}

const insertRequestTrack = `-- name: InsertRequestTrack :exec
INSERT INTO acquisition.request_tracks (request_id, recording_mbid, disc, position, title, length_ms, wanted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (request_id, recording_mbid) DO NOTHING
`

type InsertRequestTrackParams struct {
	RequestID     uuid.UUID
	RecordingMbid uuid.UUID
	Disc          int32
	Position      int32
	Title         string
	LengthMs      int32
	WantedAt      *time.Time
}

func (q *Queries) InsertRequestTrack(ctx context.Context, arg InsertRequestTrackParams) error {
	_, err := q.db.Exec(ctx, insertRequestTrack,
		arg.RequestID,
		arg.RecordingMbid,
		arg.Disc,
		arg.Position,
		arg.Title,
		arg.LengthMs,
		arg.WantedAt,
	)
	return err
}

const listByState = `-- name: ListByState :many
SELECT id, release_group_mbid, release_mbid, artist_mbid, artist_name, album_title, year, state, priority, error_code, torrent_hash, release_title, indexer, quality, file_ext, size_bytes, seeders, progress, lidarr_album_id, import_mode, attempts, requested_by, created_at, updated_at, started_at, last_progress_at, completed_at FROM acquisition.requests WHERE state = $1 ORDER BY updated_at LIMIT $2
`

type ListByStateParams struct {
	State string
	Lim   int32
}

func (q *Queries) ListByState(ctx context.Context, arg ListByStateParams) ([]AcquisitionRequest, error) {
	rows, err := q.db.Query(ctx, listByState, arg.State, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquisitionRequest
	for rows.Next() {
		var i AcquisitionRequest
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseGroupMbid,
			&i.ReleaseMbid,
			&i.ArtistMbid,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.Year,
			&i.State,
			&i.Priority,
			&i.ErrorCode,
			&i.TorrentHash,
			&i.ReleaseTitle,
			&i.Indexer,
			&i.Quality,
			&i.FileExt,
			&i.SizeBytes,
			&i.Seeders,
			&i.Progress,
			&i.LidarrAlbumID,
			&i.ImportMode,
			&i.Attempts,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.LastProgressAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT id, release_group_mbid, release_mbid, artist_mbid, artist_name, album_title, year, state, priority, error_code, torrent_hash, release_title, indexer, quality, file_ext, size_bytes, seeders, progress, lidarr_album_id, import_mode, attempts, requested_by, created_at, updated_at, started_at, last_progress_at, completed_at FROM acquisition.requests
WHERE ($1::text IS NULL OR state = $1::text)
ORDER BY updated_at DESC LIMIT $2
`

type ListRequestsParams struct {
	State *string
	Lim   int32
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]AcquisitionRequest, error) {
	rows, err := q.db.Query(ctx, listRequests, arg.State, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquisitionRequest
	for rows.Next() {
		var i AcquisitionRequest
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseGroupMbid,
			&i.ReleaseMbid,
			&i.ArtistMbid,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.Year,
			&i.State,
			&i.Priority,
			&i.ErrorCode,
			&i.TorrentHash,
			&i.ReleaseTitle,
			&i.Indexer,
			&i.Quality,
			&i.FileExt,
			&i.SizeBytes,
			&i.Seeders,
			&i.Progress,
			&i.LidarrAlbumID,
			&i.ImportMode,
			&i.Attempts,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.LastProgressAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWanted = `-- name: MarkWanted :exec
UPDATE acquisition.request_tracks SET wanted_at = now() WHERE request_id = $1 AND recording_mbid = $2
`

type MarkWantedParams struct {
	RequestID     uuid.UUID
	RecordingMbid uuid.UUID
}

func (q *Queries) MarkWanted(ctx context.Context, arg MarkWantedParams) error {
	_, err := q.db.Exec(ctx, markWanted, arg.RequestID, arg.RecordingMbid)
	return err
}

const requestByHash = `-- name: RequestByHash :one
SELECT id, release_group_mbid, release_mbid, artist_mbid, artist_name, album_title, year, state, priority, error_code, torrent_hash, release_title, indexer, quality, file_ext, size_bytes, seeders, progress, lidarr_album_id, import_mode, attempts, requested_by, created_at, updated_at, started_at, last_progress_at, completed_at FROM acquisition.requests WHERE torrent_hash = $1 ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) RequestByHash(ctx context.Context, torrentHash string) (AcquisitionRequest, error) {
	row := q.db.QueryRow(ctx, requestByHash, torrentHash)
	var i AcquisitionRequest
	err := row.Scan(
		&i.ID,
		&i.ReleaseGroupMbid,
		&i.ReleaseMbid,
		&i.ArtistMbid,
		&i.ArtistName,
		&i.AlbumTitle,
		&i.Year,
		&i.State,
		&i.Priority,
		&i.ErrorCode,
		&i.TorrentHash,
		&i.ReleaseTitle,
		&i.Indexer,
		&i.Quality,
		&i.FileExt,
		&i.SizeBytes,
		&i.Seeders,
		&i.Progress,
		&i.LidarrAlbumID,
		&i.ImportMode,
		&i.Attempts,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.LastProgressAt,
		&i.CompletedAt,
	)
	return i, err
}

const requestByID = `-- name: RequestByID :one
SELECT id, release_group_mbid, release_mbid, artist_mbid, artist_name, album_title, year, state, priority, error_code, torrent_hash, release_title, indexer, quality, file_ext, size_bytes, seeders, progress, lidarr_album_id, import_mode, attempts, requested_by, created_at, updated_at, started_at, last_progress_at, completed_at FROM acquisition.requests WHERE id = $1
`

func (q *Queries) RequestByID(ctx context.Context, id uuid.UUID) (AcquisitionRequest, error) {
	row := q.db.QueryRow(ctx, requestByID, id)
	var i AcquisitionRequest
	err := row.Scan(
		&i.ID,
		&i.ReleaseGroupMbid,
		&i.ReleaseMbid,
		&i.ArtistMbid,
		&i.ArtistName,
		&i.AlbumTitle,
		&i.Year,
		&i.State,
		&i.Priority,
		&i.ErrorCode,
		&i.TorrentHash,
		&i.ReleaseTitle,
		&i.Indexer,
		&i.Quality,
		&i.FileExt,
		&i.SizeBytes,
		&i.Seeders,
		&i.Progress,
		&i.LidarrAlbumID,
		&i.ImportMode,
		&i.Attempts,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.LastProgressAt,
		&i.CompletedAt,
	)
	return i, err
}

const requestByReleaseGroup = `-- name: RequestByReleaseGroup :one
SELECT id, release_group_mbid, release_mbid, artist_mbid, artist_name, album_title, year, state, priority, error_code, torrent_hash, release_title, indexer, quality, file_ext, size_bytes, seeders, progress, lidarr_album_id, import_mode, attempts, requested_by, created_at, updated_at, started_at, last_progress_at, completed_at FROM acquisition.requests WHERE release_group_mbid = $1
`

func (q *Queries) RequestByReleaseGroup(ctx context.Context, releaseGroupMbid uuid.UUID) (AcquisitionRequest, error) {
	row := q.db.QueryRow(ctx, requestByReleaseGroup, releaseGroupMbid)
	var i AcquisitionRequest
	err := row.Scan(
		&i.ID,
		&i.ReleaseGroupMbid,
		&i.ReleaseMbid,
		&i.ArtistMbid,
		&i.ArtistName,
		&i.AlbumTitle,
		&i.Year,
		&i.State,
		&i.Priority,
		&i.ErrorCode,
		&i.TorrentHash,
		&i.ReleaseTitle,
		&i.Indexer,
		&i.Quality,
		&i.FileExt,
		&i.SizeBytes,
		&i.Seeders,
		&i.Progress,
		&i.LidarrAlbumID,
		&i.ImportMode,
		&i.Attempts,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.LastProgressAt,
		&i.CompletedAt,
	)
	return i, err
}

const requestEvents = `-- name: RequestEvents :many
SELECT kind, user_id, detail, at FROM acquisition.events WHERE request_id = $1 ORDER BY at, id
`

type RequestEventsRow struct {
	Kind   string
	UserID *uuid.UUID
	Detail []byte
	At     time.Time
}

func (q *Queries) RequestEvents(ctx context.Context, requestID uuid.UUID) ([]RequestEventsRow, error) {
	rows, err := q.db.Query(ctx, requestEvents, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestEventsRow
	for rows.Next() {
		var i RequestEventsRow
		if err := rows.Scan(
			&i.Kind,
			&i.UserID,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestTracks = `-- name: RequestTracks :many
SELECT request_id, recording_mbid, disc, position, title, length_ms, file_index, file_name, file_size, library_path, wanted_at FROM acquisition.request_tracks WHERE request_id = $1 ORDER BY disc, position
`

func (q *Queries) RequestTracks(ctx context.Context, requestID uuid.UUID) ([]AcquisitionRequestTrack, error) {
	rows, err := q.db.Query(ctx, requestTracks, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquisitionRequestTrack
	for rows.Next() {
		var i AcquisitionRequestTrack
		if err := rows.Scan(
			&i.RequestID,
			&i.RecordingMbid,
			&i.Disc,
			&i.Position,
			&i.Title,
			&i.LengthMs,
			&i.FileIndex,
			&i.FileName,
			&i.FileSize,
			&i.LibraryPath,
			&i.WantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestUsers = `-- name: RequestUsers :many
SELECT user_id, reason, created_at FROM acquisition.request_users WHERE request_id = $1 ORDER BY created_at
`

type RequestUsersRow struct {
	UserID    uuid.UUID
	Reason    string
	CreatedAt time.Time
}

func (q *Queries) RequestUsers(ctx context.Context, requestID uuid.UUID) ([]RequestUsersRow, error) {
	rows, err := q.db.Query(ctx, requestUsers, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestUsersRow
	for rows.Next() {
		var i RequestUsersRow
		if err := rows.Scan(&i.UserID, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueFailed = `-- name: RequeueFailed :execrows
UPDATE acquisition.requests
SET state = 'queued', error_code = '', attempts = attempts + 1, torrent_hash = '', progress = 0, updated_at = now()
WHERE id = $1 AND state = 'failed'
`

func (q *Queries) RequeueFailed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requeueFailed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetStaleSearching = `-- name: ResetStaleSearching :execrows
UPDATE acquisition.requests SET state = 'queued', updated_at = now()
WHERE state = 'searching' AND updated_at < $1
`

func (q *Queries) ResetStaleSearching(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, resetStaleSearching, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDownloading = `-- name: SetDownloading :exec
UPDATE acquisition.requests
SET state = 'downloading', torrent_hash = $1, release_title = $2, indexer = $3,
    quality = $4, size_bytes = $5, seeders = $6, file_ext = $7,
    last_progress_at = now(), updated_at = now()
WHERE id = $8
`

type SetDownloadingParams struct {
	TorrentHash  string
	ReleaseTitle string
	Indexer      string
	Quality      string
	SizeBytes    int64
	Seeders      int32
	FileExt      string
	ID           uuid.UUID
}

func (q *Queries) SetDownloading(ctx context.Context, arg SetDownloadingParams) error {
	_, err := q.db.Exec(ctx, setDownloading,
		arg.TorrentHash,
		arg.ReleaseTitle,
		arg.Indexer,
		arg.Quality,
		arg.SizeBytes,
		arg.Seeders,
		arg.FileExt,
		arg.ID,
	)
	return err
}

const setImportMode = `-- name: SetImportMode :exec
UPDATE acquisition.requests SET import_mode = $1, updated_at = now() WHERE id = $2
`

type SetImportModeParams struct {
	ImportMode string
	ID         uuid.UUID
}

func (q *Queries) SetImportMode(ctx context.Context, arg SetImportModeParams) error {
	_, err := q.db.Exec(ctx, setImportMode, arg.ImportMode, arg.ID)
	return err
}

const setLidarrAlbum = `-- name: SetLidarrAlbum :exec
UPDATE acquisition.requests SET lidarr_album_id = $1, updated_at = now() WHERE id = $2
`

type SetLidarrAlbumParams struct {
	LidarrAlbumID *int32
	ID            uuid.UUID
}

func (q *Queries) SetLidarrAlbum(ctx context.Context, arg SetLidarrAlbumParams) error {
	_, err := q.db.Exec(ctx, setLidarrAlbum, arg.LidarrAlbumID, arg.ID)
	return err
}

const setProgress = `-- name: SetProgress :exec
UPDATE acquisition.requests
SET progress = $1, seeders = $2,
    last_progress_at = CASE WHEN $3::boolean THEN now() ELSE last_progress_at END, updated_at = now()
WHERE id = $4
`

type SetProgressParams struct {
	Progress float32
	Seeders  int32
	Advanced bool
	ID       uuid.UUID
}

func (q *Queries) SetProgress(ctx context.Context, arg SetProgressParams) error {
	_, err := q.db.Exec(ctx, setProgress,
		arg.Progress,
		arg.Seeders,
		arg.Advanced,
		arg.ID,
	)
	return err
}

const setState = `-- name: SetState :exec
UPDATE acquisition.requests SET state = $1, error_code = $2, updated_at = now(),
    completed_at = CASE WHEN $1 IN ('available', 'failed') THEN now() ELSE completed_at END
WHERE id = $3
`

type SetStateParams struct {
	State     string
	ErrorCode string
	ID        uuid.UUID
}

func (q *Queries) SetState(ctx context.Context, arg SetStateParams) error {
	_, err := q.db.Exec(ctx, setState, arg.State, arg.ErrorCode, arg.ID)
	return err
}

const setTrackFile = `-- name: SetTrackFile :exec
UPDATE acquisition.request_tracks SET file_index = $1, file_name = $2, file_size = $3
WHERE request_id = $4 AND recording_mbid = $5
`

type SetTrackFileParams struct {
	FileIndex     *int32
	FileName      string
	FileSize      int64
	RequestID     uuid.UUID
	RecordingMbid uuid.UUID
}

func (q *Queries) SetTrackFile(ctx context.Context, arg SetTrackFileParams) error {
	_, err := q.db.Exec(ctx, setTrackFile,
		arg.FileIndex,
		arg.FileName,
		arg.FileSize,
		arg.RequestID,
		arg.RecordingMbid,
	)
	return err
}

const setTrackLibraryPath = `-- name: SetTrackLibraryPath :exec
UPDATE acquisition.request_tracks SET library_path = $1
WHERE request_id = $2 AND recording_mbid = $3
`

type SetTrackLibraryPathParams struct {
	LibraryPath   string
	RequestID     uuid.UUID
	RecordingMbid uuid.UUID
}

func (q *Queries) SetTrackLibraryPath(ctx context.Context, arg SetTrackLibraryPathParams) error {
	_, err := q.db.Exec(ctx, setTrackLibraryPath, arg.LibraryPath, arg.RequestID, arg.RecordingMbid)
	return err
}

const trackByRecording = `-- name: TrackByRecording :one
SELECT t.request_id, t.recording_mbid, t.disc, t.position, t.title, t.length_ms, t.file_index, t.file_name, t.file_size, t.library_path, t.wanted_at, r.state, r.torrent_hash, r.error_code, r.progress, r.file_ext
FROM acquisition.request_tracks t JOIN acquisition.requests r ON r.id = t.request_id
WHERE t.recording_mbid = $1
ORDER BY (r.state = 'failed'), r.created_at DESC
LIMIT 1
`

type TrackByRecordingRow struct {
	RequestID     uuid.UUID
	RecordingMbid uuid.UUID
	Disc          int32
	Position      int32
	Title         string
	LengthMs      int32
	FileIndex     *int32
	FileName      string
	FileSize      int64
	LibraryPath   string
	WantedAt      *time.Time
	State         string
	TorrentHash   string
	ErrorCode     string
	Progress      float32
	FileExt       string
}

// The most useful request for a recording: one that is not failed, newest first.
func (q *Queries) TrackByRecording(ctx context.Context, recordingMbid uuid.UUID) (TrackByRecordingRow, error) {
	row := q.db.QueryRow(ctx, trackByRecording, recordingMbid)
	var i TrackByRecordingRow
	err := row.Scan(
		&i.RequestID,
		&i.RecordingMbid,
		&i.Disc,
		&i.Position,
		&i.Title,
		&i.LengthMs,
		&i.FileIndex,
		&i.FileName,
		&i.FileSize,
		&i.LibraryPath,
		&i.WantedAt,
		&i.State,
		&i.TorrentHash,
		&i.ErrorCode,
		&i.Progress,
		&i.FileExt,
	)
	return i, err
}
