#!/usr/bin/env bash
# DEV ONLY: create a local .env (git-ignored) with random dev secrets.
# Telegram/ngrok tokens are NOT written here — they are loaded at runtime from
# the root secrets file by tools/dev/load-secrets.sh.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="$ROOT/.env"
if [[ -f "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo ".env exists (use --force to regenerate)"; exit 0
fi
rnd() { head -c "${1:-32}" /dev/urandom | base64 | tr -d '/+=\n' | head -c "${2:-43}"; }
PGPASS="$(rnd 24 32)"
MINIOPASS="$(rnd 24 32)"
umask 077
cat > "$ENV_FILE" <<ENV
# Generated by tools/dev/gen-dev-env.sh — DEV ONLY, git-ignored.
APP_ENV=dev
LOG_LEVEL=debug
POSTGRES_USER=tapenest
POSTGRES_PASSWORD=$PGPASS
POSTGRES_DB=tapenest
POSTGRES_PORT=5432
DATABASE_URL=postgres://tapenest:$PGPASS@127.0.0.1:5432/tapenest?sslmode=disable
TEST_DATABASE_URL=postgres://tapenest:$PGPASS@127.0.0.1:5432/tapenest_test?sslmode=disable
REDIS_PORT=6379
TEST_REDIS_URL=redis://127.0.0.1:6379/15
REDIS_URL=redis://127.0.0.1:6379/0
API_GATEWAY_PORT=8080
BOT_SERVICE_PORT=8081
GATEWAY_URL=http://127.0.0.1:8080
JWT_SECRET=$(rnd 48 64)
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=720h
INITDATA_TTL=24h
INTERNAL_API_TOKEN=$(rnd 32 43)
TELEGRAM_WEBHOOK_SECRET=$(rnd 32 43)
CORS_ALLOWED_ORIGINS=http://localhost:5173,https://*.ngrok-free.app,https://*.ngrok.app
TRUST_PROXY_HEADERS=true
RATE_LIMIT_RPS=10
RATE_LIMIT_BURST=40
AUTH_RATE_LIMIT_RPS=1
AUTH_RATE_LIMIT_BURST=20
ADMIN_TELEGRAM_IDS=
MUSIC_SERVICE_URL=http://127.0.0.1:8084
MUSIC_SERVICE_PORT=8084
MUSIC_WORKER_PORT=8085
STREAM_SIGNING_KEY=$(rnd 48 64)
STREAM_URL_TTL=1h
NAVIDROME_PORT=4533
NAVIDROME_URL=http://127.0.0.1:4533
NAVIDROME_USER=admin
NAVIDROME_PASSWORD=$(rnd 24 32)
MUSIC_DIR=/workspace/.devdata/music
DOWNLOAD_SERVICE_URL=http://127.0.0.1:8082
DOWNLOAD_SERVICE_PORT=8082
DOWNLOAD_WORKER_PORT=8083
MINIO_ROOT_USER=tapenest
MINIO_ROOT_PASSWORD=$MINIOPASS
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001
LIDARR_URL=http://127.0.0.1:8686
LIDARR_API_KEY=$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')
PROWLARR_URL=http://127.0.0.1:9696
PROWLARR_API_KEY=$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')
QBITTORRENT_URL=http://127.0.0.1:8092
QBITTORRENT_USER=tapenest
QBITTORRENT_PASSWORD=$(rnd 24 32)
TORRENT_DIR=/workspace/.devdata/torrents
ACQUISITION_SERVICE_URL=http://127.0.0.1:8088
ACQUISITION_SERVICE_PORT=8088
ACQUISITION_WORKER_PORT=8089
CONTENT_SOURCES=p2p
S3_ENDPOINT=127.0.0.1:9000
S3_ACCESS_KEY=tapenest
S3_SECRET_KEY=$MINIOPASS
S3_USE_SSL=false
S3_BUCKET_MEDIA=media
PRESIGN_TTL=1h
YTDLP_JS_RUNTIMES=deno
STREAMING_SERVICE_URL=
ENV
echo "wrote $ENV_FILE"
