// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLiveMediaRefs = `-- name: CountLiveMediaRefs :one
SELECT count(*)::int FROM download.jobs WHERE media_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveMediaRefs(ctx context.Context, mediaID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveMediaRefs, mediaID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserJobs = `-- name: CountUserJobs :one
SELECT count(*) FILTER (WHERE status IN ('queued', 'running') AND deleted_at IS NULL)::int AS active,
       count(*) FILTER (WHERE created_at > $1::timestamptz)::int AS recent
FROM download.jobs
WHERE user_id = $2
  AND (status IN ('queued', 'running') OR created_at > $1::timestamptz)
`

type CountUserJobsParams struct {
	Since  time.Time
	UserID uuid.UUID
}

type CountUserJobsRow struct {
	Active int32
	Recent int32
}

func (q *Queries) CountUserJobs(ctx context.Context, arg CountUserJobsParams) (CountUserJobsRow, error) {
	row := q.db.QueryRow(ctx, countUserJobs, arg.Since, arg.UserID)
	var i CountUserJobsRow
	err := row.Scan(&i.Active, &i.Recent)
	return i, err
}

const findActiveUserJob = `-- name: FindActiveUserJob :one
SELECT user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at FROM download.jobs
WHERE user_id = $1 AND url_hash = $2 AND status IN ('queued', 'running') AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type FindActiveUserJobParams struct {
	UserID  uuid.UUID
	UrlHash string
}

func (q *Queries) FindActiveUserJob(ctx context.Context, arg FindActiveUserJobParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, findActiveUserJob, arg.UserID, arg.UrlHash)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const finishDone = `-- name: FinishDone :one
UPDATE download.jobs
SET status = 'done', stage = '', media_id = $2, title = $3, error_kind = '', error_message = '',
    updated_at = now(), finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at
`

type FinishDoneParams struct {
	ID      uuid.UUID
	MediaID *uuid.UUID
	Title   string
}

func (q *Queries) FinishDone(ctx context.Context, arg FinishDoneParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, finishDone, arg.ID, arg.MediaID, arg.Title)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const finishFailed = `-- name: FinishFailed :one
UPDATE download.jobs
SET status = 'failed', stage = '', error_kind = $2, error_message = $3, updated_at = now(), finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at
`

type FinishFailedParams struct {
	ID           uuid.UUID
	ErrorKind    string
	ErrorMessage string
}

func (q *Queries) FinishFailed(ctx context.Context, arg FinishFailedParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, finishFailed, arg.ID, arg.ErrorKind, arg.ErrorMessage)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at FROM download.jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, url_hash, normalized_url, source, external_id, title, duration_sec, width, height, format_id, object_key, size_bytes, mime_type, thumbnail_url, created_at, expires_at, poster_key FROM download.media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (DownloadMedium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i DownloadMedium
	err := row.Scan(
		&i.ID,
		&i.UrlHash,
		&i.NormalizedUrl,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.DurationSec,
		&i.Width,
		&i.Height,
		&i.FormatID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.MimeType,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PosterKey,
	)
	return i, err
}

const getMediaByHash = `-- name: GetMediaByHash :one
SELECT id, url_hash, normalized_url, source, external_id, title, duration_sec, width, height, format_id, object_key, size_bytes, mime_type, thumbnail_url, created_at, expires_at, poster_key FROM download.media WHERE url_hash = $1 AND expires_at > now()
`

func (q *Queries) GetMediaByHash(ctx context.Context, urlHash string) (DownloadMedium, error) {
	row := q.db.QueryRow(ctx, getMediaByHash, urlHash)
	var i DownloadMedium
	err := row.Scan(
		&i.ID,
		&i.UrlHash,
		&i.NormalizedUrl,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.DurationSec,
		&i.Width,
		&i.Height,
		&i.FormatID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.MimeType,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PosterKey,
	)
	return i, err
}

const getUserJob = `-- name: GetUserJob :one
SELECT user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at FROM download.jobs WHERE user_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetUserJobParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetUserJob(ctx context.Context, arg GetUserJobParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, getUserJob, arg.UserID, arg.ID)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO download.jobs (user_id, id, url, normalized_url, url_hash, source, status, priority,
                           media_id, title, chat_id, status_message_id, reply_to_message_id, lang, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at
`

type InsertJobParams struct {
	UserID           uuid.UUID
	ID               uuid.UUID
	Url              string
	NormalizedUrl    string
	UrlHash          string
	Source           string
	Status           string
	Priority         string
	MediaID          *uuid.UUID
	Title            string
	ChatID           *int64
	StatusMessageID  *int64
	ReplyToMessageID *int64
	Lang             string
	FinishedAt       *time.Time
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.UserID,
		arg.ID,
		arg.Url,
		arg.NormalizedUrl,
		arg.UrlHash,
		arg.Source,
		arg.Status,
		arg.Priority,
		arg.MediaID,
		arg.Title,
		arg.ChatID,
		arg.StatusMessageID,
		arg.ReplyToMessageID,
		arg.Lang,
		arg.FinishedAt,
	)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const listUserJobs = `-- name: ListUserJobs :many
SELECT user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at FROM download.jobs
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListUserJobsParams struct {
	UserID        uuid.UUID
	BeforeCreated *time.Time
	BeforeID      *uuid.UUID
	Lim           int32
}

func (q *Queries) ListUserJobs(ctx context.Context, arg ListUserJobsParams) ([]DownloadJob, error) {
	rows, err := q.db.Query(ctx, listUserJobs,
		arg.UserID,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownloadJob
	for rows.Next() {
		var i DownloadJob
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Url,
			&i.NormalizedUrl,
			&i.UrlHash,
			&i.Source,
			&i.Status,
			&i.Stage,
			&i.Priority,
			&i.Attempts,
			&i.ErrorKind,
			&i.ErrorMessage,
			&i.MediaID,
			&i.Title,
			&i.ChatID,
			&i.StatusMessageID,
			&i.ReplyToMessageID,
			&i.Lang,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.DisplayTitle,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunning = `-- name: MarkRunning :one
UPDATE download.jobs
SET status = 'running', stage = $2, attempts = attempts + 1, updated_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at
`

type MarkRunningParams struct {
	ID    uuid.UUID
	Stage string
}

func (q *Queries) MarkRunning(ctx context.Context, arg MarkRunningParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, markRunning, arg.ID, arg.Stage)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const renameJob = `-- name: RenameJob :one
UPDATE download.jobs
SET display_title = $3, updated_at = now()
WHERE user_id = $1 AND id = $2 AND deleted_at IS NULL AND status = 'done'
RETURNING user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at
`

type RenameJobParams struct {
	UserID       uuid.UUID
	ID           uuid.UUID
	DisplayTitle string
}

func (q *Queries) RenameJob(ctx context.Context, arg RenameJobParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, renameJob, arg.UserID, arg.ID, arg.DisplayTitle)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const requeue = `-- name: Requeue :one
UPDATE download.jobs
SET status = 'queued', stage = '', priority = $2, error_kind = $3, error_message = $4, updated_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at
`

type RequeueParams struct {
	ID           uuid.UUID
	Priority     string
	ErrorKind    string
	ErrorMessage string
}

func (q *Queries) Requeue(ctx context.Context, arg RequeueParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, requeue,
		arg.ID,
		arg.Priority,
		arg.ErrorKind,
		arg.ErrorMessage,
	)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const setPosterKey = `-- name: SetPosterKey :exec
UPDATE download.media SET poster_key = $2 WHERE id = $1
`

type SetPosterKeyParams struct {
	ID        uuid.UUID
	PosterKey string
}

func (q *Queries) SetPosterKey(ctx context.Context, arg SetPosterKeyParams) error {
	_, err := q.db.Exec(ctx, setPosterKey, arg.ID, arg.PosterKey)
	return err
}

const setStage = `-- name: SetStage :exec
UPDATE download.jobs SET stage = $1, title = CASE WHEN $2::text = '' THEN title ELSE $2::text END, updated_at = now()
WHERE id = $3 AND status = 'running'
`

type SetStageParams struct {
	Stage string
	Title string
	ID    uuid.UUID
}

func (q *Queries) SetStage(ctx context.Context, arg SetStageParams) error {
	_, err := q.db.Exec(ctx, setStage, arg.Stage, arg.Title, arg.ID)
	return err
}

const softDeleteJob = `-- name: SoftDeleteJob :one
UPDATE download.jobs
SET deleted_at = now(), updated_at = now()
WHERE user_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING user_id, id, url, normalized_url, url_hash, source, status, stage, priority, attempts, error_kind, error_message, media_id, title, chat_id, status_message_id, reply_to_message_id, lang, created_at, updated_at, finished_at, display_title, deleted_at
`

type SoftDeleteJobParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) SoftDeleteJob(ctx context.Context, arg SoftDeleteJobParams) (DownloadJob, error) {
	row := q.db.QueryRow(ctx, softDeleteJob, arg.UserID, arg.ID)
	var i DownloadJob
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.UrlHash,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempts,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.MediaID,
		&i.Title,
		&i.ChatID,
		&i.StatusMessageID,
		&i.ReplyToMessageID,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DisplayTitle,
		&i.DeletedAt,
	)
	return i, err
}

const upsertMedia = `-- name: UpsertMedia :one
INSERT INTO download.media (id, url_hash, normalized_url, source, external_id, title, duration_sec, width, height,
                            format_id, object_key, size_bytes, mime_type, thumbnail_url, poster_key, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (url_hash) DO UPDATE
SET normalized_url = EXCLUDED.normalized_url, title = EXCLUDED.title,
    duration_sec = EXCLUDED.duration_sec, width = EXCLUDED.width, height = EXCLUDED.height,
    format_id = EXCLUDED.format_id, object_key = EXCLUDED.object_key, size_bytes = EXCLUDED.size_bytes,
    mime_type = EXCLUDED.mime_type, thumbnail_url = EXCLUDED.thumbnail_url,
    poster_key = CASE WHEN EXCLUDED.poster_key <> '' THEN EXCLUDED.poster_key ELSE download.media.poster_key END,
    created_at = now(), expires_at = EXCLUDED.expires_at
RETURNING id, url_hash, normalized_url, source, external_id, title, duration_sec, width, height, format_id, object_key, size_bytes, mime_type, thumbnail_url, created_at, expires_at, poster_key
`

type UpsertMediaParams struct {
	ID            uuid.UUID
	UrlHash       string
	NormalizedUrl string
	Source        string
	ExternalID    string
	Title         string
	DurationSec   int32
	Width         int32
	Height        int32
	FormatID      string
	ObjectKey     string
	SizeBytes     int64
	MimeType      string
	ThumbnailUrl  string
	PosterKey     string
	ExpiresAt     time.Time
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (DownloadMedium, error) {
	row := q.db.QueryRow(ctx, upsertMedia,
		arg.ID,
		arg.UrlHash,
		arg.NormalizedUrl,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.DurationSec,
		arg.Width,
		arg.Height,
		arg.FormatID,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.MimeType,
		arg.ThumbnailUrl,
		arg.PosterKey,
		arg.ExpiresAt,
	)
	var i DownloadMedium
	err := row.Scan(
		&i.ID,
		&i.UrlHash,
		&i.NormalizedUrl,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.DurationSec,
		&i.Width,
		&i.Height,
		&i.FormatID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.MimeType,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PosterKey,
	)
	return i, err
}
