// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type DownloadJob struct {
	UserID           uuid.UUID
	ID               uuid.UUID
	Url              string
	NormalizedUrl    string
	UrlHash          string
	Source           string
	Status           string
	Stage            string
	Priority         string
	Attempts         int32
	ErrorKind        string
	ErrorMessage     string
	MediaID          *uuid.UUID
	Title            string
	ChatID           *int64
	StatusMessageID  *int64
	ReplyToMessageID *int64
	Lang             string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	FinishedAt       *time.Time
	DisplayTitle     string
	DeletedAt        *time.Time
}

type DownloadMedium struct {
	ID            uuid.UUID
	UrlHash       string
	NormalizedUrl string
	Source        string
	ExternalID    string
	Title         string
	DurationSec   int32
	Width         int32
	Height        int32
	FormatID      string
	ObjectKey     string
	SizeBytes     int64
	MimeType      string
	ThumbnailUrl  string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	PosterKey     string
}
