// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquiredFileSizes = `-- name: AcquiredFileSizes :many
SELECT size_bytes, mb_recording_id, mb_release_group_id FROM music.acquired_files
`

type AcquiredFileSizesRow struct {
	SizeBytes        int64
	MbRecordingID    uuid.UUID
	MbReleaseGroupID *uuid.UUID
}

func (q *Queries) AcquiredFileSizes(ctx context.Context) ([]AcquiredFileSizesRow, error) {
	rows, err := q.db.Query(ctx, acquiredFileSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquiredFileSizesRow
	for rows.Next() {
		var i AcquiredFileSizesRow
		if err := rows.Scan(&i.SizeBytes, &i.MbRecordingID, &i.MbReleaseGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const albumByID = `-- name: AlbumByID :one
SELECT a.id, a.title, a.year, a.cover_art_id, a.mbid, a.artist_id, coalesce(ar.name, '')::text AS artist_name,
       (a.navidrome_id IS NULL)::boolean AS remote, coalesce(a.youtube_browse_id, '')::text AS youtube_browse_id
FROM music.albums a LEFT JOIN music.artists ar ON ar.id = a.artist_id WHERE a.id = $1
`

type AlbumByIDRow struct {
	ID              uuid.UUID
	Title           string
	Year            int32
	CoverArtID      string
	Mbid            *uuid.UUID
	ArtistID        *uuid.UUID
	ArtistName      string
	Remote          bool
	YoutubeBrowseID string
}

func (q *Queries) AlbumByID(ctx context.Context, id uuid.UUID) (AlbumByIDRow, error) {
	row := q.db.QueryRow(ctx, albumByID, id)
	var i AlbumByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.CoverArtID,
		&i.Mbid,
		&i.ArtistID,
		&i.ArtistName,
		&i.Remote,
		&i.YoutubeBrowseID,
	)
	return i, err
}

const albumTracks = `-- name: AlbumTracks :many
SELECT t.id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec,
       (l.user_id IS NOT NULL)::boolean AS liked, (t.navidrome_id IS NULL)::boolean AS remote
FROM music.tracks t
LEFT JOIN music.likes l ON l.user_id = $1 AND l.track_id = t.id
WHERE t.album_id = $2 AND t.deleted_at IS NULL
ORDER BY t.track_no, t.title LIMIT 500
`

type AlbumTracksParams struct {
	UserID  uuid.UUID
	AlbumID *uuid.UUID
}

type AlbumTracksRow struct {
	ID          uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Liked       bool
	Remote      bool
}

func (q *Queries) AlbumTracks(ctx context.Context, arg AlbumTracksParams) ([]AlbumTracksRow, error) {
	rows, err := q.db.Query(ctx, albumTracks, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumTracksRow
	for rows.Next() {
		var i AlbumTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Liked,
			&i.Remote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const artistAlbums = `-- name: ArtistAlbums :many
SELECT a.id, a.title, a.year, a.cover_art_id, a.mbid, (a.navidrome_id IS NULL)::boolean AS remote
FROM music.albums a WHERE a.artist_id = $1
ORDER BY a.year DESC, a.title LIMIT 200
`

type ArtistAlbumsRow struct {
	ID         uuid.UUID
	Title      string
	Year       int32
	CoverArtID string
	Mbid       *uuid.UUID
	Remote     bool
}

func (q *Queries) ArtistAlbums(ctx context.Context, artistID *uuid.UUID) ([]ArtistAlbumsRow, error) {
	rows, err := q.db.Query(ctx, artistAlbums, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistAlbumsRow
	for rows.Next() {
		var i ArtistAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.CoverArtID,
			&i.Mbid,
			&i.Remote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const artistByID = `-- name: ArtistByID :one
SELECT id, name, mbid, (navidrome_id IS NULL)::boolean AS remote,
       coalesce(youtube_browse_id, '')::text AS youtube_browse_id
FROM music.artists WHERE id = $1
`

type ArtistByIDRow struct {
	ID              uuid.UUID
	Name            string
	Mbid            *uuid.UUID
	Remote          bool
	YoutubeBrowseID string
}

func (q *Queries) ArtistByID(ctx context.Context, id uuid.UUID) (ArtistByIDRow, error) {
	row := q.db.QueryRow(ctx, artistByID, id)
	var i ArtistByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mbid,
		&i.Remote,
		&i.YoutubeBrowseID,
	)
	return i, err
}

const artistIDByNavidrome = `-- name: ArtistIDByNavidrome :one
SELECT id FROM music.artists WHERE navidrome_id = $1
`

func (q *Queries) ArtistIDByNavidrome(ctx context.Context, navidromeID *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, artistIDByNavidrome, navidromeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const artistTracks = `-- name: ArtistTracks :many
SELECT t.id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec,
       (l.user_id IS NOT NULL)::boolean AS liked, (t.navidrome_id IS NULL)::boolean AS remote
FROM music.tracks t
LEFT JOIN music.track_popularity p ON p.track_id = t.id
LEFT JOIN music.likes l ON l.user_id = $1 AND l.track_id = t.id
WHERE t.artist_id = $2 AND t.deleted_at IS NULL
ORDER BY (t.navidrome_id IS NOT NULL) DESC, coalesce(p.score, 0) DESC, t.title LIMIT $3
`

type ArtistTracksParams struct {
	UserID   uuid.UUID
	ArtistID *uuid.UUID
	Lim      int32
}

type ArtistTracksRow struct {
	ID          uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Liked       bool
	Remote      bool
}

func (q *Queries) ArtistTracks(ctx context.Context, arg ArtistTracksParams) ([]ArtistTracksRow, error) {
	rows, err := q.db.Query(ctx, artistTracks, arg.UserID, arg.ArtistID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistTracksRow
	for rows.Next() {
		var i ArtistTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Liked,
			&i.Remote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimAlbum = `-- name: ClaimAlbum :exec
UPDATE music.albums a SET navidrome_id = $1, updated_at = now()
WHERE a.id = $2 AND a.navidrome_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM music.albums x WHERE x.navidrome_id = $1)
`

type ClaimAlbumParams struct {
	NavidromeID *string
	ID          uuid.UUID
}

func (q *Queries) ClaimAlbum(ctx context.Context, arg ClaimAlbumParams) error {
	_, err := q.db.Exec(ctx, claimAlbum, arg.NavidromeID, arg.ID)
	return err
}

const claimArtist = `-- name: ClaimArtist :exec
UPDATE music.artists a SET navidrome_id = $1, updated_at = now()
WHERE a.id = $2 AND a.navidrome_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM music.artists x WHERE x.navidrome_id = $1)
`

type ClaimArtistParams struct {
	NavidromeID *string
	ID          uuid.UUID
}

func (q *Queries) ClaimArtist(ctx context.Context, arg ClaimArtistParams) error {
	_, err := q.db.Exec(ctx, claimArtist, arg.NavidromeID, arg.ID)
	return err
}

const claimByRecording = `-- name: ClaimByRecording :one
UPDATE music.tracks SET navidrome_id = $1, updated_at = now()
WHERE mb_recording_id = $2 AND navidrome_id IS NULL
RETURNING id, album_id, artist_id
`

type ClaimByRecordingParams struct {
	NavidromeID   *string
	MbRecordingID *uuid.UUID
}

type ClaimByRecordingRow struct {
	ID       uuid.UUID
	AlbumID  *uuid.UUID
	ArtistID *uuid.UUID
}

// Placeholder whose MusicBrainz recording id matches the file's tag.
func (q *Queries) ClaimByRecording(ctx context.Context, arg ClaimByRecordingParams) (ClaimByRecordingRow, error) {
	row := q.db.QueryRow(ctx, claimByRecording, arg.NavidromeID, arg.MbRecordingID)
	var i ClaimByRecordingRow
	err := row.Scan(&i.ID, &i.AlbumID, &i.ArtistID)
	return i, err
}

const claimBySize = `-- name: ClaimBySize :one
UPDATE music.tracks t SET navidrome_id = $1, updated_at = now()
WHERE t.navidrome_id IS NULL AND t.mb_recording_id = (
    SELECT f.mb_recording_id FROM music.acquired_files f
    JOIN music.tracks p ON p.mb_recording_id = f.mb_recording_id AND p.navidrome_id IS NULL
    WHERE f.size_bytes = $2
    ORDER BY f.created_at DESC LIMIT 1)
RETURNING t.id, t.album_id, t.artist_id
`

type ClaimBySizeParams struct {
	NavidromeID *string
	SizeBytes   int64
}

type ClaimBySizeRow struct {
	ID       uuid.UUID
	AlbumID  *uuid.UUID
	ArtistID *uuid.UUID
}

// Placeholder of a file acquisition-service imported with exactly this size.
func (q *Queries) ClaimBySize(ctx context.Context, arg ClaimBySizeParams) (ClaimBySizeRow, error) {
	row := q.db.QueryRow(ctx, claimBySize, arg.NavidromeID, arg.SizeBytes)
	var i ClaimBySizeRow
	err := row.Scan(&i.ID, &i.AlbumID, &i.ArtistID)
	return i, err
}

const countActiveTracks = `-- name: CountActiveTracks :one
SELECT count(*) FROM music.tracks WHERE deleted_at IS NULL AND navidrome_id IS NOT NULL
`

func (q *Queries) CountActiveTracks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTracks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const coverExists = `-- name: CoverExists :one
SELECT EXISTS (SELECT 1 FROM music.tracks WHERE cover_art_id = $1 AND deleted_at IS NULL)
`

func (q *Queries) CoverExists(ctx context.Context, coverArtID string) (bool, error) {
	row := q.db.QueryRow(ctx, coverExists, coverArtID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ensurePlayEventsPartition = `-- name: EnsurePlayEventsPartition :one
SELECT music.ensure_play_events_partition($1::date)::text
`

func (q *Queries) EnsurePlayEventsPartition(ctx context.Context, month pgtype.Date) (string, error) {
	row := q.db.QueryRow(ctx, ensurePlayEventsPartition, month)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const exportCatalog = `-- name: ExportCatalog :many
SELECT t.id, t.title, coalesce(t.artist_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS artist_id,
       t.artist_name, t.album_id, t.album_title, t.genre, t.year, t.duration_sec,
       coalesce(p.score, 0)::double precision AS popularity, t.created_at
FROM music.tracks t
LEFT JOIN music.track_popularity p ON p.track_id = t.id
WHERE t.deleted_at IS NULL AND t.navidrome_id IS NOT NULL AND ($1::uuid IS NULL OR t.id > $1::uuid)
ORDER BY t.id
LIMIT $2
`

type ExportCatalogParams struct {
	After *uuid.UUID
	Lim   int32
}

type ExportCatalogRow struct {
	ID          uuid.UUID
	Title       string
	ArtistID    uuid.UUID
	ArtistName  string
	AlbumID     *uuid.UUID
	AlbumTitle  string
	Genre       string
	Year        *int32
	DurationSec int32
	Popularity  float64
	CreatedAt   time.Time
}

// Internal catalog export for reco-service (keyset by id).
func (q *Queries) ExportCatalog(ctx context.Context, arg ExportCatalogParams) ([]ExportCatalogRow, error) {
	rows, err := q.db.Query(ctx, exportCatalog, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportCatalogRow
	for rows.Next() {
		var i ExportCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.AlbumID,
			&i.AlbumTitle,
			&i.Genre,
			&i.Year,
			&i.DurationSec,
			&i.Popularity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAcquiredFile = `-- name: InsertAcquiredFile :exec
INSERT INTO music.acquired_files (path, mb_recording_id, mb_release_group_id, size_bytes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (path) DO UPDATE SET mb_recording_id = EXCLUDED.mb_recording_id,
    mb_release_group_id = EXCLUDED.mb_release_group_id, size_bytes = EXCLUDED.size_bytes
`

type InsertAcquiredFileParams struct {
	Path             string
	MbRecordingID    uuid.UUID
	MbReleaseGroupID *uuid.UUID
	SizeBytes        int64
}

func (q *Queries) InsertAcquiredFile(ctx context.Context, arg InsertAcquiredFileParams) error {
	_, err := q.db.Exec(ctx, insertAcquiredFile,
		arg.Path,
		arg.MbRecordingID,
		arg.MbReleaseGroupID,
		arg.SizeBytes,
	)
	return err
}

const listPopular = `-- name: ListPopular :many
SELECT t.id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec,
       (l.user_id IS NOT NULL)::boolean AS liked,
       coalesce(p.score, 0)::double precision AS score
FROM music.tracks t
LEFT JOIN music.track_popularity p ON p.track_id = t.id
LEFT JOIN music.likes l ON l.user_id = $1 AND l.track_id = t.id
WHERE t.deleted_at IS NULL AND t.navidrome_id IS NOT NULL
  AND ($2::double precision IS NULL
       OR (coalesce(p.score, 0), t.id) < ($2::double precision, $3::uuid))
ORDER BY coalesce(p.score, 0) DESC, t.id DESC
LIMIT $4
`

type ListPopularParams struct {
	UserID      uuid.UUID
	CursorScore *float64
	CursorID    *uuid.UUID
	Lim         int32
}

type ListPopularRow struct {
	ID          uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Liked       bool
	Score       float64
}

func (q *Queries) ListPopular(ctx context.Context, arg ListPopularParams) ([]ListPopularRow, error) {
	rows, err := q.db.Query(ctx, listPopular,
		arg.UserID,
		arg.CursorScore,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPopularRow
	for rows.Next() {
		var i ListPopularRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Liked,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnsyncedTracksDeleted = `-- name: MarkUnsyncedTracksDeleted :execrows
UPDATE music.tracks SET deleted_at = now(), updated_at = now()
WHERE synced_at < $1 AND deleted_at IS NULL AND navidrome_id IS NOT NULL
`

func (q *Queries) MarkUnsyncedTracksDeleted(ctx context.Context, syncedBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, markUnsyncedTracksDeleted, syncedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const navidromeTrackExists = `-- name: NavidromeTrackExists :one
SELECT EXISTS (SELECT 1 FROM music.tracks WHERE navidrome_id = $1)
`

func (q *Queries) NavidromeTrackExists(ctx context.Context, navidromeID *string) (bool, error) {
	row := q.db.QueryRow(ctx, navidromeTrackExists, navidromeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const refreshPopularity = `-- name: RefreshPopularity :exec
REFRESH MATERIALIZED VIEW CONCURRENTLY music.track_popularity
`

func (q *Queries) RefreshPopularity(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshPopularity)
	return err
}

const revertUnsyncedToRemote = `-- name: RevertUnsyncedToRemote :execrows
UPDATE music.tracks SET navidrome_id = NULL, size_bytes = 0, bitrate = 0,
    cover_art_id = CASE WHEN mb_release_group_id IS NULL THEN cover_art_id ELSE 'caa-' || mb_release_group_id::text END,
    updated_at = now()
WHERE synced_at < $1 AND deleted_at IS NULL AND navidrome_id IS NOT NULL AND mb_recording_id IS NOT NULL
`

// A vanished file whose MusicBrainz recording is known becomes a placeholder
// again (same UUID: likes/playlists survive, playing re-acquires it).
func (q *Queries) RevertUnsyncedToRemote(ctx context.Context, syncedBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, revertUnsyncedToRemote, syncedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchAlbums = `-- name: SearchAlbums :many
SELECT a.id, a.title, a.year, a.cover_art_id, coalesce(ar.name, '')::text AS artist_name, a.artist_id, a.mbid,
       (a.navidrome_id IS NULL)::boolean AS remote,
       word_similarity($1::text, lower(a.title || ' ' || coalesce(ar.name, '')))::double precision AS score
FROM music.albums a LEFT JOIN music.artists ar ON ar.id = a.artist_id
WHERE $1::text <% lower(a.title || ' ' || coalesce(ar.name, '')) OR lower(a.title) LIKE $2::text
ORDER BY score DESC, a.id LIMIT $3
`

type SearchAlbumsParams struct {
	Q       string
	Pattern string
	Lim     int32
}

type SearchAlbumsRow struct {
	ID         uuid.UUID
	Title      string
	Year       int32
	CoverArtID string
	ArtistName string
	ArtistID   *uuid.UUID
	Mbid       *uuid.UUID
	Remote     bool
	Score      float64
}

func (q *Queries) SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]SearchAlbumsRow, error) {
	rows, err := q.db.Query(ctx, searchAlbums, arg.Q, arg.Pattern, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAlbumsRow
	for rows.Next() {
		var i SearchAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.CoverArtID,
			&i.ArtistName,
			&i.ArtistID,
			&i.Mbid,
			&i.Remote,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArtists = `-- name: SearchArtists :many
SELECT ar.id, ar.name, ar.mbid, (ar.navidrome_id IS NULL)::boolean AS remote,
       word_similarity($1::text, lower(ar.name))::double precision AS score
FROM music.artists ar
WHERE $1::text <% lower(ar.name) OR lower(ar.name) LIKE $2::text
ORDER BY score DESC, ar.id LIMIT $3
`

type SearchArtistsParams struct {
	Q       string
	Pattern string
	Lim     int32
}

type SearchArtistsRow struct {
	ID     uuid.UUID
	Name   string
	Mbid   *uuid.UUID
	Remote bool
	Score  float64
}

func (q *Queries) SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]SearchArtistsRow, error) {
	rows, err := q.db.Query(ctx, searchArtists, arg.Q, arg.Pattern, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArtistsRow
	for rows.Next() {
		var i SearchArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mbid,
			&i.Remote,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTracks = `-- name: SearchTracks :many
SELECT t.id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec,
       (l.user_id IS NOT NULL)::boolean AS liked, (t.navidrome_id IS NULL)::boolean AS remote,
       word_similarity($1::text, t.search_text)::double precision AS score
FROM music.tracks t
LEFT JOIN music.likes l ON l.user_id = $2 AND l.track_id = t.id
WHERE t.deleted_at IS NULL
  AND ($1::text <% t.search_text OR t.search_text LIKE $3::text)
  AND ($4::double precision IS NULL
       OR (word_similarity($1::text, t.search_text)::double precision, t.id)
          < ($4::double precision, $5::uuid))
ORDER BY word_similarity($1::text, t.search_text)::double precision DESC, t.id DESC
LIMIT $6
`

type SearchTracksParams struct {
	Q           string
	UserID      uuid.UUID
	Pattern     string
	CursorScore *float64
	CursorID    *uuid.UUID
	Lim         int32
}

type SearchTracksRow struct {
	ID          uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Liked       bool
	Remote      bool
	Score       float64
}

// word_similarity (pg_trgm, GIN) for fuzzy matches + ILIKE for short substrings.
func (q *Queries) SearchTracks(ctx context.Context, arg SearchTracksParams) ([]SearchTracksRow, error) {
	rows, err := q.db.Query(ctx, searchTracks,
		arg.Q,
		arg.UserID,
		arg.Pattern,
		arg.CursorScore,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTracksRow
	for rows.Next() {
		var i SearchTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Liked,
			&i.Remote,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlbumMBID = `-- name: SetAlbumMBID :exec
UPDATE music.albums a SET mbid = $1, updated_at = now()
WHERE a.id = $2 AND a.mbid IS NULL
  AND NOT EXISTS (SELECT 1 FROM music.albums x WHERE x.mbid = $1)
`

type SetAlbumMBIDParams struct {
	Mbid *uuid.UUID
	ID   uuid.UUID
}

// Library album of an acquired release group (unless another album owns the id).
func (q *Queries) SetAlbumMBID(ctx context.Context, arg SetAlbumMBIDParams) error {
	_, err := q.db.Exec(ctx, setAlbumMBID, arg.Mbid, arg.ID)
	return err
}

const trackForStream = `-- name: TrackForStream :one
SELECT id, navidrome_id, content_type, size_bytes, mb_recording_id, mb_release_group_id, title,
       coalesce(youtube_video_id, '')::text AS youtube_video_id
FROM music.tracks
WHERE id = $1 AND deleted_at IS NULL
`

type TrackForStreamRow struct {
	ID               uuid.UUID
	NavidromeID      *string
	ContentType      string
	SizeBytes        int64
	MbRecordingID    *uuid.UUID
	MbReleaseGroupID *uuid.UUID
	Title            string
	YoutubeVideoID   string
}

func (q *Queries) TrackForStream(ctx context.Context, id uuid.UUID) (TrackForStreamRow, error) {
	row := q.db.QueryRow(ctx, trackForStream, id)
	var i TrackForStreamRow
	err := row.Scan(
		&i.ID,
		&i.NavidromeID,
		&i.ContentType,
		&i.SizeBytes,
		&i.MbRecordingID,
		&i.MbReleaseGroupID,
		&i.Title,
		&i.YoutubeVideoID,
	)
	return i, err
}

const tracksByIDs = `-- name: TracksByIDs :many
SELECT t.id, (t.navidrome_id IS NULL)::boolean AS remote, coalesce(t.artist_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS artist_id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec,
       (l.user_id IS NOT NULL)::boolean AS liked
FROM music.tracks t
LEFT JOIN music.likes l ON l.user_id = $1 AND l.track_id = t.id
WHERE t.id = ANY($2::uuid[]) AND t.deleted_at IS NULL
`

type TracksByIDsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

type TracksByIDsRow struct {
	ID          uuid.UUID
	Remote      bool
	ArtistID    uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Liked       bool
}

func (q *Queries) TracksByIDs(ctx context.Context, arg TracksByIDsParams) ([]TracksByIDsRow, error) {
	rows, err := q.db.Query(ctx, tracksByIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TracksByIDsRow
	for rows.Next() {
		var i TracksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Remote,
			&i.ArtistID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Liked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbum = `-- name: UpsertAlbum :one
INSERT INTO music.albums (id, navidrome_id, artist_id, title, year, cover_art_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (navidrome_id) DO UPDATE SET
    artist_id = EXCLUDED.artist_id, title = EXCLUDED.title, year = EXCLUDED.year,
    cover_art_id = EXCLUDED.cover_art_id, updated_at = now()
RETURNING id
`

type UpsertAlbumParams struct {
	ID          uuid.UUID
	NavidromeID *string
	ArtistID    *uuid.UUID
	Title       string
	Year        int32
	CoverArtID  string
}

func (q *Queries) UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAlbum,
		arg.ID,
		arg.NavidromeID,
		arg.ArtistID,
		arg.Title,
		arg.Year,
		arg.CoverArtID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertArtist = `-- name: UpsertArtist :one
INSERT INTO music.artists (id, navidrome_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (navidrome_id) DO UPDATE SET name = EXCLUDED.name, updated_at = now()
    WHERE music.artists.name IS DISTINCT FROM EXCLUDED.name
RETURNING id
`

type UpsertArtistParams struct {
	ID          uuid.UUID
	NavidromeID *string
	Name        string
}

func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertArtist, arg.ID, arg.NavidromeID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertRemoteAlbum = `-- name: UpsertRemoteAlbum :one
INSERT INTO music.albums (id, mbid, artist_id, title, year, cover_art_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (mbid) DO UPDATE SET artist_id = coalesce(music.albums.artist_id, EXCLUDED.artist_id)
RETURNING id
`

type UpsertRemoteAlbumParams struct {
	ID         uuid.UUID
	Mbid       *uuid.UUID
	ArtistID   *uuid.UUID
	Title      string
	Year       int32
	CoverArtID string
}

func (q *Queries) UpsertRemoteAlbum(ctx context.Context, arg UpsertRemoteAlbumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertRemoteAlbum,
		arg.ID,
		arg.Mbid,
		arg.ArtistID,
		arg.Title,
		arg.Year,
		arg.CoverArtID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertRemoteArtist = `-- name: UpsertRemoteArtist :one

INSERT INTO music.artists (id, mbid, name) VALUES ($1, $2, $3)
ON CONFLICT (mbid) DO UPDATE SET updated_at = music.artists.updated_at
RETURNING id
`

type UpsertRemoteArtistParams struct {
	ID   uuid.UUID
	Mbid *uuid.UUID
	Name string
}

// ── remote catalog (MusicBrainz placeholders, ADR 0011) ─────────────────────
func (q *Queries) UpsertRemoteArtist(ctx context.Context, arg UpsertRemoteArtistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertRemoteArtist, arg.ID, arg.Mbid, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertRemoteTrack = `-- name: UpsertRemoteTrack :one
INSERT INTO music.tracks (id, mb_recording_id, mb_release_group_id, mb_artist_id, album_id, artist_id, title,
                          artist_name, album_title, track_no, duration_sec, cover_art_id, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, now())
ON CONFLICT (mb_recording_id) DO UPDATE SET
    album_id = coalesce(music.tracks.album_id, EXCLUDED.album_id),
    track_no = CASE WHEN music.tracks.navidrome_id IS NULL AND music.tracks.track_no = 0 THEN EXCLUDED.track_no ELSE music.tracks.track_no END,
    mb_release_group_id = coalesce(music.tracks.mb_release_group_id, EXCLUDED.mb_release_group_id)
RETURNING id
`

type UpsertRemoteTrackParams struct {
	ID               uuid.UUID
	MbRecordingID    *uuid.UUID
	MbReleaseGroupID *uuid.UUID
	MbArtistID       *uuid.UUID
	AlbumID          *uuid.UUID
	ArtistID         *uuid.UUID
	Title            string
	ArtistName       string
	AlbumTitle       string
	TrackNo          int32
	DurationSec      int32
	CoverArtID       string
}

// First write wins for metadata; album/position are filled in when an album
// view later provides them.
func (q *Queries) UpsertRemoteTrack(ctx context.Context, arg UpsertRemoteTrackParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertRemoteTrack,
		arg.ID,
		arg.MbRecordingID,
		arg.MbReleaseGroupID,
		arg.MbArtistID,
		arg.AlbumID,
		arg.ArtistID,
		arg.Title,
		arg.ArtistName,
		arg.AlbumTitle,
		arg.TrackNo,
		arg.DurationSec,
		arg.CoverArtID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertTrack = `-- name: UpsertTrack :one
INSERT INTO music.tracks (id, navidrome_id, album_id, artist_id, title, artist_name, album_title, track_no,
                          duration_sec, cover_art_id, content_type, size_bytes, bitrate, genre, year, synced_at,
                          mb_recording_id, mb_release_group_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $15, $16,
        (SELECT $17::uuid WHERE NOT EXISTS (
            SELECT 1 FROM music.tracks x WHERE x.mb_recording_id = $17::uuid)),
        $18)
ON CONFLICT (navidrome_id) DO UPDATE SET
    mb_recording_id = COALESCE(music.tracks.mb_recording_id, EXCLUDED.mb_recording_id),
    mb_release_group_id = COALESCE(music.tracks.mb_release_group_id, EXCLUDED.mb_release_group_id),
    album_id = EXCLUDED.album_id, artist_id = EXCLUDED.artist_id, title = EXCLUDED.title,
    artist_name = EXCLUDED.artist_name, album_title = EXCLUDED.album_title, track_no = EXCLUDED.track_no,
    duration_sec = EXCLUDED.duration_sec, cover_art_id = EXCLUDED.cover_art_id,
    content_type = EXCLUDED.content_type, size_bytes = EXCLUDED.size_bytes, bitrate = EXCLUDED.bitrate,
    genre = EXCLUDED.genre, year = EXCLUDED.year,
    synced_at = EXCLUDED.synced_at, deleted_at = NULL, updated_at = now()
RETURNING id
`

type UpsertTrackParams struct {
	ID               uuid.UUID
	NavidromeID      *string
	AlbumID          *uuid.UUID
	ArtistID         *uuid.UUID
	Title            string
	ArtistName       string
	AlbumTitle       string
	TrackNo          int32
	DurationSec      int32
	CoverArtID       string
	ContentType      string
	SizeBytes        int64
	Bitrate          int32
	Genre            string
	Year             *int32
	SyncedAt         time.Time
	MbRecordingID    *uuid.UUID
	MbReleaseGroupID *uuid.UUID
}

// mb_recording_id (file tag or acquired-file size match) is attached only when no
// other row owns it yet, so a MusicBrainz search never duplicates a library track.
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTrack,
		arg.ID,
		arg.NavidromeID,
		arg.AlbumID,
		arg.ArtistID,
		arg.Title,
		arg.ArtistName,
		arg.AlbumTitle,
		arg.TrackNo,
		arg.DurationSec,
		arg.CoverArtID,
		arg.ContentType,
		arg.SizeBytes,
		arg.Bitrate,
		arg.Genre,
		arg.Year,
		arg.SyncedAt,
		arg.MbRecordingID,
		arg.MbReleaseGroupID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertYouTubeAlbum = `-- name: UpsertYouTubeAlbum :one
INSERT INTO music.albums (id, artist_id, title, year, cover_art_id, youtube_browse_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (youtube_browse_id) DO UPDATE SET
    artist_id = coalesce(music.albums.artist_id, EXCLUDED.artist_id),
    cover_art_id = CASE WHEN music.albums.cover_art_id = '' THEN EXCLUDED.cover_art_id ELSE music.albums.cover_art_id END
RETURNING id
`

type UpsertYouTubeAlbumParams struct {
	ID              uuid.UUID
	ArtistID        *uuid.UUID
	Title           string
	Year            int32
	CoverArtID      string
	YoutubeBrowseID *string
}

func (q *Queries) UpsertYouTubeAlbum(ctx context.Context, arg UpsertYouTubeAlbumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertYouTubeAlbum,
		arg.ID,
		arg.ArtistID,
		arg.Title,
		arg.Year,
		arg.CoverArtID,
		arg.YoutubeBrowseID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertYouTubeArtist = `-- name: UpsertYouTubeArtist :one
INSERT INTO music.artists (id, name, youtube_browse_id)
VALUES ($1, $2, $3)
ON CONFLICT (youtube_browse_id) DO UPDATE SET name = EXCLUDED.name, updated_at = now()
RETURNING id
`

type UpsertYouTubeArtistParams struct {
	ID              uuid.UUID
	Name            string
	YoutubeBrowseID *string
}

func (q *Queries) UpsertYouTubeArtist(ctx context.Context, arg UpsertYouTubeArtistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertYouTubeArtist, arg.ID, arg.Name, arg.YoutubeBrowseID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertYouTubeTrack = `-- name: UpsertYouTubeTrack :one
INSERT INTO music.tracks (id, album_id, artist_id, title, artist_name, album_title, track_no, duration_sec, cover_art_id, youtube_video_id, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (youtube_video_id) DO UPDATE SET
    album_id = coalesce(music.tracks.album_id, EXCLUDED.album_id),
    artist_id = coalesce(music.tracks.artist_id, EXCLUDED.artist_id),
    duration_sec = CASE WHEN music.tracks.duration_sec = 0 THEN EXCLUDED.duration_sec ELSE music.tracks.duration_sec END,
    track_no = CASE WHEN music.tracks.track_no = 0 THEN EXCLUDED.track_no ELSE music.tracks.track_no END,
    cover_art_id = CASE WHEN music.tracks.cover_art_id = '' THEN EXCLUDED.cover_art_id ELSE music.tracks.cover_art_id END
RETURNING id
`

type UpsertYouTubeTrackParams struct {
	ID             uuid.UUID
	AlbumID        *uuid.UUID
	ArtistID       *uuid.UUID
	Title          string
	ArtistName     string
	AlbumTitle     string
	TrackNo        int32
	DurationSec    int32
	CoverArtID     string
	YoutubeVideoID *string
}

func (q *Queries) UpsertYouTubeTrack(ctx context.Context, arg UpsertYouTubeTrackParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertYouTubeTrack,
		arg.ID,
		arg.AlbumID,
		arg.ArtistID,
		arg.Title,
		arg.ArtistName,
		arg.AlbumTitle,
		arg.TrackNo,
		arg.DurationSec,
		arg.CoverArtID,
		arg.YoutubeVideoID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const waveCandidates = `-- name: WaveCandidates :many
SELECT t.id, coalesce(t.artist_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS artist_id,
       coalesce(p.score, 0)::double precision AS popularity,
       (l.user_id IS NOT NULL)::boolean AS liked,
       EXISTS (SELECT 1 FROM music.likes l2 JOIN music.tracks t2 ON t2.id = l2.track_id
               WHERE l2.user_id = $1 AND t2.artist_id = t.artist_id)::boolean AS liked_artist,
       r.played_at AS last_played
FROM music.tracks t
LEFT JOIN music.track_popularity p ON p.track_id = t.id
LEFT JOIN music.likes l ON l.user_id = $1 AND l.track_id = t.id
LEFT JOIN music.recent_plays r ON r.user_id = $1 AND r.track_id = t.id
WHERE t.deleted_at IS NULL AND t.navidrome_id IS NOT NULL
ORDER BY coalesce(p.score, 0) DESC, t.id
LIMIT $2
`

type WaveCandidatesParams struct {
	UserID uuid.UUID
	Lim    int32
}

type WaveCandidatesRow struct {
	ID          uuid.UUID
	ArtistID    uuid.UUID
	Popularity  float64
	Liked       bool
	LikedArtist bool
	LastPlayed  *time.Time
}

// "My wave" MVP (spec §4.1, §5.4): popularity + likes + artist affinity + recency.
func (q *Queries) WaveCandidates(ctx context.Context, arg WaveCandidatesParams) ([]WaveCandidatesRow, error) {
	rows, err := q.db.Query(ctx, waveCandidates, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaveCandidatesRow
	for rows.Next() {
		var i WaveCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Popularity,
			&i.Liked,
			&i.LikedArtist,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
