// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPlaylistTrack = `-- name: AddPlaylistTrack :execrows
INSERT INTO music.playlist_tracks (user_id, playlist_id, track_id, position)
SELECT p.user_id, p.id, t.id,
       coalesce((SELECT max(pt.position) FROM music.playlist_tracks pt WHERE pt.playlist_id = p.id), 0) + 1
FROM music.playlists p, music.tracks t
WHERE p.user_id = $1 AND p.id = $2 AND t.id = $3 AND t.deleted_at IS NULL
ON CONFLICT (playlist_id, track_id) DO NOTHING
`

type AddPlaylistTrackParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

func (q *Queries) AddPlaylistTrack(ctx context.Context, arg AddPlaylistTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, addPlaylistTrack, arg.UserID, arg.PlaylistID, arg.TrackID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPlaylists = `-- name: CountPlaylists :one
SELECT count(*) FROM music.playlists WHERE user_id = $1
`

func (q *Queries) CountPlaylists(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylists, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO music.playlists (user_id, id, title) VALUES ($1, $2, $3)
RETURNING id, title, created_at
`

type CreatePlaylistParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Title  string
}

type CreatePlaylistRow struct {
	ID        uuid.UUID
	Title     string
	CreatedAt time.Time
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (CreatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.UserID, arg.ID, arg.Title)
	var i CreatePlaylistRow
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :execrows
DELETE FROM music.playlists WHERE user_id = $1 AND id = $2
`

type DeletePlaylistParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlaylist, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportLikes = `-- name: ExportLikes :many
SELECT user_id, track_id, created_at FROM music.likes ORDER BY created_at
`

func (q *Queries) ExportLikes(ctx context.Context) ([]MusicLike, error) {
	rows, err := q.db.Query(ctx, exportLikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusicLike
	for rows.Next() {
		var i MusicLike
		if err := rows.Scan(&i.UserID, &i.TrackID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPlayEvents = `-- name: ExportPlayEvents :many
SELECT user_id, track_id, played_at, position_sec, completed, event_id FROM music.play_events
WHERE played_at >= $1 ORDER BY played_at
`

func (q *Queries) ExportPlayEvents(ctx context.Context, since time.Time) ([]MusicPlayEvent, error) {
	rows, err := q.db.Query(ctx, exportPlayEvents, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusicPlayEvent
	for rows.Next() {
		var i MusicPlayEvent
		if err := rows.Scan(
			&i.UserID,
			&i.TrackID,
			&i.PlayedAt,
			&i.PositionSec,
			&i.Completed,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPlaylistAdds = `-- name: ExportPlaylistAdds :many
SELECT p.user_id, pt.track_id, pt.added_at FROM music.playlist_tracks pt
JOIN music.playlists p ON p.id = pt.playlist_id
ORDER BY pt.added_at
`

type ExportPlaylistAddsRow struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
	AddedAt time.Time
}

func (q *Queries) ExportPlaylistAdds(ctx context.Context) ([]ExportPlaylistAddsRow, error) {
	rows, err := q.db.Query(ctx, exportPlaylistAdds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportPlaylistAddsRow
	for rows.Next() {
		var i ExportPlaylistAddsRow
		if err := rows.Scan(&i.UserID, &i.TrackID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT p.id, p.title, p.created_at, (SELECT count(*) FROM music.playlist_tracks pt WHERE pt.playlist_id = p.id)::bigint AS track_count
FROM music.playlists p WHERE p.user_id = $1 AND p.id = $2
`

type GetPlaylistParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetPlaylistRow struct {
	ID         uuid.UUID
	Title      string
	CreatedAt  time.Time
	TrackCount int64
}

func (q *Queries) GetPlaylist(ctx context.Context, arg GetPlaylistParams) (GetPlaylistRow, error) {
	row := q.db.QueryRow(ctx, getPlaylist, arg.UserID, arg.ID)
	var i GetPlaylistRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.TrackCount,
	)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT track_id, position_sec, updated_at FROM music.playback_positions
WHERE user_id = $1 AND track_id = $2
`

type GetPositionParams struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

type GetPositionRow struct {
	TrackID     uuid.UUID
	PositionSec float64
	UpdatedAt   time.Time
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (GetPositionRow, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.UserID, arg.TrackID)
	var i GetPositionRow
	err := row.Scan(&i.TrackID, &i.PositionSec, &i.UpdatedAt)
	return i, err
}

const insertPlayEvents = `-- name: InsertPlayEvents :execrows
INSERT INTO music.play_events (user_id, track_id, played_at, position_sec, completed, event_id)
SELECT e.user_id, e.track_id, e.played_at, e.position_sec, e.completed, e.event_id
FROM (SELECT unnest($1::uuid[]) AS user_id, unnest($2::uuid[]) AS track_id,
             unnest($3::timestamptz[]) AS played_at, unnest($4::real[]) AS position_sec,
             unnest($5::boolean[]) AS completed, unnest($6::text[]) AS event_id) e
JOIN music.tracks t ON t.id = e.track_id
ON CONFLICT (event_id, played_at) DO NOTHING
`

type InsertPlayEventsParams struct {
	UserIds        []uuid.UUID
	TrackIds       []uuid.UUID
	PlayedAts      []time.Time
	Positions      []float32
	CompletedFlags []bool
	EventIds       []string
}

// Batch from the batcher; unknown tracks are dropped; redelivery is a no-op.
func (q *Queries) InsertPlayEvents(ctx context.Context, arg InsertPlayEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPlayEvents,
		arg.UserIds,
		arg.TrackIds,
		arg.PlayedAts,
		arg.Positions,
		arg.CompletedFlags,
		arg.EventIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const likeTrack = `-- name: LikeTrack :execrows
INSERT INTO music.likes (user_id, track_id)
SELECT $1, t.id FROM music.tracks t WHERE t.id = $2 AND t.deleted_at IS NULL
ON CONFLICT (user_id, track_id) DO NOTHING
`

type LikeTrackParams struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

func (q *Queries) LikeTrack(ctx context.Context, arg LikeTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, likeTrack, arg.UserID, arg.TrackID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLiked = `-- name: ListLiked :many
SELECT t.id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec, (t.navidrome_id IS NULL)::boolean AS remote,
       true::boolean AS liked, l.created_at AS sort_at
FROM music.likes l
JOIN music.tracks t ON t.id = l.track_id AND t.deleted_at IS NULL
WHERE l.user_id = $1
  AND ($2::timestamptz IS NULL
       OR (l.created_at, l.track_id) < ($2::timestamptz, $3::uuid))
ORDER BY l.created_at DESC, l.track_id DESC
LIMIT $4
`

type ListLikedParams struct {
	UserID   uuid.UUID
	CursorAt *time.Time
	CursorID *uuid.UUID
	Lim      int32
}

type ListLikedRow struct {
	ID          uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Remote      bool
	Liked       bool
	SortAt      time.Time
}

func (q *Queries) ListLiked(ctx context.Context, arg ListLikedParams) ([]ListLikedRow, error) {
	rows, err := q.db.Query(ctx, listLiked,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLikedRow
	for rows.Next() {
		var i ListLikedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Remote,
			&i.Liked,
			&i.SortAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylists = `-- name: ListPlaylists :many
SELECT p.id, p.title, p.created_at, (SELECT count(*) FROM music.playlist_tracks pt WHERE pt.playlist_id = p.id)::bigint AS track_count
FROM music.playlists p
WHERE p.user_id = $1
ORDER BY p.created_at DESC, p.id DESC
LIMIT 500
`

type ListPlaylistsRow struct {
	ID         uuid.UUID
	Title      string
	CreatedAt  time.Time
	TrackCount int64
}

func (q *Queries) ListPlaylists(ctx context.Context, userID uuid.UUID) ([]ListPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistsRow
	for rows.Next() {
		var i ListPlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecent = `-- name: ListRecent :many
SELECT t.id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec, (t.navidrome_id IS NULL)::boolean AS remote,
       (l.user_id IS NOT NULL)::boolean AS liked, r.played_at AS sort_at
FROM music.recent_plays r
JOIN music.tracks t ON t.id = r.track_id AND t.deleted_at IS NULL
LEFT JOIN music.likes l ON l.user_id = r.user_id AND l.track_id = r.track_id
WHERE r.user_id = $1
  AND ($2::timestamptz IS NULL
       OR (r.played_at, r.track_id) < ($2::timestamptz, $3::uuid))
ORDER BY r.played_at DESC, r.track_id DESC
LIMIT $4
`

type ListRecentParams struct {
	UserID   uuid.UUID
	CursorAt *time.Time
	CursorID *uuid.UUID
	Lim      int32
}

type ListRecentRow struct {
	ID          uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Remote      bool
	Liked       bool
	SortAt      time.Time
}

func (q *Queries) ListRecent(ctx context.Context, arg ListRecentParams) ([]ListRecentRow, error) {
	rows, err := q.db.Query(ctx, listRecent,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentRow
	for rows.Next() {
		var i ListRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Remote,
			&i.Liked,
			&i.SortAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playlistTrackExists = `-- name: PlaylistTrackExists :one
SELECT EXISTS (SELECT 1 FROM music.playlist_tracks WHERE playlist_id = $1 AND track_id = $2)
`

type PlaylistTrackExistsParams struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

func (q *Queries) PlaylistTrackExists(ctx context.Context, arg PlaylistTrackExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, playlistTrackExists, arg.PlaylistID, arg.TrackID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const playlistTracks = `-- name: PlaylistTracks :many
SELECT t.id, t.title, t.artist_name, t.album_title, t.cover_art_id, t.duration_sec, (t.navidrome_id IS NULL)::boolean AS remote,
       (l.user_id IS NOT NULL)::boolean AS liked
FROM music.playlist_tracks pt
JOIN music.tracks t ON t.id = pt.track_id AND t.deleted_at IS NULL
LEFT JOIN music.likes l ON l.user_id = pt.user_id AND l.track_id = t.id
WHERE pt.user_id = $1 AND pt.playlist_id = $2
ORDER BY pt.position, pt.added_at
LIMIT 2000
`

type PlaylistTracksParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
}

type PlaylistTracksRow struct {
	ID          uuid.UUID
	Title       string
	ArtistName  string
	AlbumTitle  string
	CoverArtID  string
	DurationSec int32
	Remote      bool
	Liked       bool
}

func (q *Queries) PlaylistTracks(ctx context.Context, arg PlaylistTracksParams) ([]PlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, playlistTracks, arg.UserID, arg.PlaylistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaylistTracksRow
	for rows.Next() {
		var i PlaylistTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.CoverArtID,
			&i.DurationSec,
			&i.Remote,
			&i.Liked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlaylistTrack = `-- name: RemovePlaylistTrack :exec
DELETE FROM music.playlist_tracks WHERE user_id = $1 AND playlist_id = $2 AND track_id = $3
`

type RemovePlaylistTrackParams struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

func (q *Queries) RemovePlaylistTrack(ctx context.Context, arg RemovePlaylistTrackParams) error {
	_, err := q.db.Exec(ctx, removePlaylistTrack, arg.UserID, arg.PlaylistID, arg.TrackID)
	return err
}

const renamePlaylist = `-- name: RenamePlaylist :execrows
UPDATE music.playlists SET title = $1, updated_at = now()
WHERE user_id = $2 AND id = $3
`

type RenamePlaylistParams struct {
	Title  string
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) RenamePlaylist(ctx context.Context, arg RenamePlaylistParams) (int64, error) {
	result, err := q.db.Exec(ctx, renamePlaylist, arg.Title, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchRecent = `-- name: TouchRecent :exec
INSERT INTO music.recent_plays (user_id, track_id, played_at)
SELECT $1, t.id, $2 FROM music.tracks t WHERE t.id = $3
ON CONFLICT (user_id, track_id) DO UPDATE SET played_at = GREATEST(music.recent_plays.played_at, EXCLUDED.played_at)
`

type TouchRecentParams struct {
	UserID   uuid.UUID
	PlayedAt time.Time
	TrackID  uuid.UUID
}

func (q *Queries) TouchRecent(ctx context.Context, arg TouchRecentParams) error {
	_, err := q.db.Exec(ctx, touchRecent, arg.UserID, arg.PlayedAt, arg.TrackID)
	return err
}

const touchRecentBatch = `-- name: TouchRecentBatch :exec
INSERT INTO music.recent_plays (user_id, track_id, played_at)
SELECT e.user_id, e.track_id, max(e.played_at)
FROM (SELECT unnest($1::uuid[]) AS user_id, unnest($2::uuid[]) AS track_id,
             unnest($3::timestamptz[]) AS played_at) e
JOIN music.tracks t ON t.id = e.track_id
GROUP BY e.user_id, e.track_id
ON CONFLICT (user_id, track_id) DO UPDATE SET played_at = GREATEST(music.recent_plays.played_at, EXCLUDED.played_at)
`

type TouchRecentBatchParams struct {
	UserIds   []uuid.UUID
	TrackIds  []uuid.UUID
	PlayedAts []time.Time
}

func (q *Queries) TouchRecentBatch(ctx context.Context, arg TouchRecentBatchParams) error {
	_, err := q.db.Exec(ctx, touchRecentBatch, arg.UserIds, arg.TrackIds, arg.PlayedAts)
	return err
}

const trackActive = `-- name: TrackActive :one
SELECT EXISTS (SELECT 1 FROM music.tracks WHERE id = $1 AND deleted_at IS NULL)
`

func (q *Queries) TrackActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, trackActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unlikeTrack = `-- name: UnlikeTrack :exec
DELETE FROM music.likes WHERE user_id = $1 AND track_id = $2
`

type UnlikeTrackParams struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

func (q *Queries) UnlikeTrack(ctx context.Context, arg UnlikeTrackParams) error {
	_, err := q.db.Exec(ctx, unlikeTrack, arg.UserID, arg.TrackID)
	return err
}

const upsertPosition = `-- name: UpsertPosition :execrows
INSERT INTO music.playback_positions (user_id, track_id, position_sec, updated_at)
SELECT $1, t.id, $2, $3 FROM music.tracks t WHERE t.id = $4 AND t.deleted_at IS NULL
ON CONFLICT (user_id, track_id) DO UPDATE SET position_sec = EXCLUDED.position_sec, updated_at = EXCLUDED.updated_at
`

type UpsertPositionParams struct {
	UserID      uuid.UUID
	PositionSec float64
	At          time.Time
	TrackID     uuid.UUID
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPosition,
		arg.UserID,
		arg.PositionSec,
		arg.At,
		arg.TrackID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
