// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type MusicAcquiredFile struct {
	Path             string
	MbRecordingID    uuid.UUID
	MbReleaseGroupID *uuid.UUID
	SizeBytes        int64
	CreatedAt        time.Time
}

type MusicAlbum struct {
	ID              uuid.UUID
	NavidromeID     *string
	ArtistID        *uuid.UUID
	Title           string
	Year            int32
	CoverArtID      string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Mbid            *uuid.UUID
	YoutubeBrowseID *string
}

type MusicArtist struct {
	ID              uuid.UUID
	NavidromeID     *string
	Name            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Mbid            *uuid.UUID
	YoutubeBrowseID *string
}

type MusicLike struct {
	UserID    uuid.UUID
	TrackID   uuid.UUID
	CreatedAt time.Time
}

type MusicPlayEvent struct {
	UserID      uuid.UUID
	TrackID     uuid.UUID
	PlayedAt    time.Time
	PositionSec float32
	Completed   bool
	EventID     string
}

type MusicPlayEventsDefault struct {
	UserID      uuid.UUID
	TrackID     uuid.UUID
	PlayedAt    time.Time
	PositionSec float32
	Completed   bool
	EventID     string
}

type MusicPlaybackPosition struct {
	UserID      uuid.UUID
	TrackID     uuid.UUID
	PositionSec float64
	UpdatedAt   time.Time
}

type MusicPlaylist struct {
	UserID    uuid.UUID
	ID        uuid.UUID
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MusicPlaylistTrack struct {
	UserID     uuid.UUID
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
	Position   int32
	AddedAt    time.Time
}

type MusicRecentPlay struct {
	UserID   uuid.UUID
	TrackID  uuid.UUID
	PlayedAt time.Time
}

type MusicTrack struct {
	ID               uuid.UUID
	NavidromeID      *string
	AlbumID          *uuid.UUID
	ArtistID         *uuid.UUID
	Title            string
	ArtistName       string
	AlbumTitle       string
	TrackNo          int32
	DurationSec      int32
	CoverArtID       string
	ContentType      string
	SizeBytes        int64
	Bitrate          int32
	SearchText       *string
	SyncedAt         time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
	Genre            string
	Year             *int32
	MbRecordingID    *uuid.UUID
	MbReleaseGroupID *uuid.UUID
	MbArtistID       *uuid.UUID
	YoutubeVideoID   *string
}

type MusicTrackPopularity struct {
	TrackID      uuid.UUID
	Plays30d     int64
	Completed30d int64
	Likes        int64
	Score        float64
}
