// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type GatewayUser struct {
	ID           uuid.UUID
	TelegramID   int64
	FirstName    string
	LastName     *string
	Username     *string
	PhotoUrl     *string
	LanguageCode *string
	IsPremium    bool
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLoginAt  *time.Time
}
