// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, telegram_id, first_name, last_name, username, photo_url, language_code, is_premium, role, created_at, updated_at, last_login_at FROM gateway.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GatewayUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GatewayUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhotoUrl,
		&i.LanguageCode,
		&i.IsPremium,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, first_name, last_name, username, photo_url, language_code, is_premium, role, created_at, updated_at, last_login_at FROM gateway.users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (GatewayUser, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i GatewayUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhotoUrl,
		&i.LanguageCode,
		&i.IsPremium,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one
INSERT INTO gateway.users (
    id, telegram_id, first_name, last_name, username, photo_url, language_code, is_premium, role, last_login_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
ON CONFLICT (telegram_id) DO UPDATE SET
    first_name    = EXCLUDED.first_name,
    last_name     = EXCLUDED.last_name,
    username      = EXCLUDED.username,
    photo_url     = COALESCE(EXCLUDED.photo_url, gateway.users.photo_url),
    language_code = COALESCE(EXCLUDED.language_code, gateway.users.language_code),
    is_premium    = EXCLUDED.is_premium,
    role          = EXCLUDED.role,
    last_login_at = COALESCE(EXCLUDED.last_login_at, gateway.users.last_login_at),
    updated_at    = now()
RETURNING id, telegram_id, first_name, last_name, username, photo_url, language_code, is_premium, role, created_at, updated_at, last_login_at
`

type UpsertTelegramUserParams struct {
	ID           uuid.UUID
	TelegramID   int64
	FirstName    string
	LastName     *string
	Username     *string
	PhotoUrl     *string
	LanguageCode *string
	IsPremium    bool
	Role         string
	LastLoginAt  *time.Time
}

func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (GatewayUser, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser,
		arg.ID,
		arg.TelegramID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.PhotoUrl,
		arg.LanguageCode,
		arg.IsPremium,
		arg.Role,
		arg.LastLoginAt,
	)
	var i GatewayUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhotoUrl,
		&i.LanguageCode,
		&i.IsPremium,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
